/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.3.0.0 (Preview)                                     */
/*  Date (dd.mm.yyyy):  1. 9.2023   Time (hh:mm): 16:34                        */
/*******************************************************************************/


#ifndef _GUIX_DROP_LIST_PRIMARY_RESOURCES_H_
#define _GUIX_DROP_LIST_PRIMARY_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define PRIMARY 0
#define PRIMARY_COLOR_FORMAT GX_COLOR_FORMAT_24XRGB
#define PRIMARY_X_RESOLUTION 640
#define PRIMARY_Y_RESOLUTION 480
#define PRIMARY_THEME_1 0
#define PRIMARY_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define PRIMARY_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_ORANGE 29
#define GX_COLOR_ID_BLACK 30
#define GX_COLOR_ID_WHITE 31
#define GX_COLOR_ID_NEXT_BUTTON_UPPER 32
#define GX_COLOR_ID_NEXT_BUTTON_LOWER 33
#define GX_COLOR_ID_TEAL 34
#define GX_COLOR_ID_LIGHT_GRAY 35
#define GX_COLOR_ID_DARK_GRAY 36
#define GX_COLOR_ID_DARK_TEAL 37
#define PRIMARY_COLOR_TABLE_SIZE 38

/* Font ID definitions                                                         */

#define GX_FONT_ID_TITLE 4
#define GX_FONT_ID_LARGE_FONT 5
#define GX_FONT_ID_SCROLL_WHEEL_NORMAL 6
#define GX_FONT_ID_SCROLL_WHEEL_SELECTED 7
#define PRIMARY_FONT_TABLE_SIZE 8

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_DROP_LIST_BUTTON 5
#define GX_PIXELMAP_ID_I_PATIENTLIST_LG 6
#define GX_PIXELMAP_ID_LIST_SCROLL_THUMB 7
#define PRIMARY_PIXELMAP_TABLE_SIZE 8

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_52 1
#define GX_STRING_ID_STRING_71 2
#define PRIMARY_STRING_TABLE_SIZE 3

#endif                                       /* sentry                         */
