/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.3.0.0 (Preview)                                     */
/*  Date (dd.mm.yyyy):  4. 9.2023   Time (hh:mm): 11:04                        */
/*******************************************************************************/


#ifndef _STANDALONE_BINRES_LOAD_EXTENDED_UNICODE_32BPP_DISPLAY_1_RESOURCES_H_
#define _STANDALONE_BINRES_LOAD_EXTENDED_UNICODE_32BPP_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

#if !defined(GX_UTF8_SUPPORT)
#error "The symbol GX_UTF8_SUPPORT must be defined to support the Studio project settings".
#endif
#if !defined(GX_EXTENDED_UNICODE_SUPPORT)
#error "The symbol GX_EXTENDED_UNICODE_SUPPORT must be defined to support the Studio project settings".
#endif

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_24XRGB
#define DISPLAY_1_X_RESOLUTION 640
#define DISPLAY_1_Y_RESOLUTION 480
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define DISPLAY_1_COLOR_TABLE_SIZE 29

/* Font ID definitions                                                         */

#define DISPLAY_1_FONT_TABLE_SIZE 4

/* Pixelmap ID definitions                                                     */

#define DISPLAY_1_PIXELMAP_TABLE_SIZE 5

/* String Ids                                                                  */

#define GX_STRING_ID_EXTENDED_UNICODES 1
#define GX_STRING_ID_STRING_6 2
#define GX_STRING_ID_STRING_4 3
#define DISPLAY_1_STRING_TABLE_SIZE 4

#endif                                       /* sentry                         */
