/***************************************************************************
 * Copyright (c) 2024 Microsoft Corporation
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **************************************************************************/
// Some portions generated by Codex (OpenAI GPT-5.5).

#pragma once
#include "express_dialog.h"

#define MAX_RECENT_PROJECTS 5
#define RECENT_WINDOW_WIDTH 700
#define RECENT_WINDOW_HEIGHT 220

class recent_list_frame : public CWnd
{
    public:
        recent_list_frame(CWnd* parent = NULL);
        ~recent_list_frame();
        void UpdateRecentList();
        void UpdateDpiResources(int dpi = 0);
        int GetPreferredHeight();

    private:
        DECLARE_MESSAGE_MAP()
        afx_msg int OnCreate(LPCREATESTRUCT lpCreateStruct);
        afx_msg void OnMouseMove(UINT nFlags, CPoint point);
        afx_msg void OnLButtonDown(UINT nFlags, CPoint point);
        afx_msg HBRUSH OnCtlColor(CDC* pDC, CWnd* pWnd, UINT nCtlColor);
        afx_msg BOOL OnEraseBkgnd(CDC* pDC);
        virtual BOOL PreTranslateMessage(MSG* pMsg);
        afx_msg void OnSetFocus(CWnd* pOldWnd);
        afx_msg void OnKillFocus(CWnd* pNewWnd);
        int FindStatic(CPoint point);
        int GetRowHeight();
        void LayoutItems();

    private:
        CStatic mRecentList[MAX_RECENT_PROJECTS];
        int     mHighlightRow;
        int     m_dpi;
        CBrush  mHiBrush;
        CBrush  mBgBrush;
        CBrush  mGrayBrush; 
        int     mNumRecentProjects;
};

class recent_project_win : public express_dialog
{
    public:
        recent_project_win(int width, int height, CWnd* pParent = NULL);   // standard constructor
        virtual ~recent_project_win();
        void UpdateRecentList();
        void UpdateDpiResources(int dpi = 0);
        static CRect GetCreateNewProjectButtonSize(CRect& parentSize);

    protected:
        DECLARE_MESSAGE_MAP()
        afx_msg int OnCreate(LPCREATESTRUCT lpCreateStruct);
        afx_msg void OnShowWindow(BOOL, UINT);
        afx_msg void OnBnClickedCreateProject();
        afx_msg void OnSettingChange(UINT uFlags, LPCTSTR lpszSection);
        afx_msg LRESULT OnDpiChanged(WPARAM wParam, LPARAM lParam);
        virtual BOOL PreTranslateMessage(MSG* pMsg);
        void LayoutControls();

private:
        recent_list_frame    mRecentListFrame;
        custom_bitmap_button new_button;
};
