/***************************************************************************
 * Copyright (c) 2024 Microsoft Corporation
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **************************************************************************/
// Some portions generated by Codex (OpenAI GPT-5.5).

#include "studiox_includes.h"
#include "splash_screen.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif

extern     CString studiox_version_string;
extern CFont TitleFont;
extern CFont TinyFont;
extern CFont NormalFont;

#define SPLASH_PRODUCT_NAME _T("Eclipse ThreadX GUIX Studio")
#define SPLASH_TEXT_LEFT_96DPI 200
#define SPLASH_TEXT_TOP_96DPI 120
#define SPLASH_TEXT_RIGHT_MARGIN_96DPI 10

BEGIN_MESSAGE_MAP(splash_screen, CDialog)
	ON_WM_PAINT()
    ON_WM_CREATE()
    ON_WM_TIMER()
    ON_BN_CLICKED(IDOK, OnDoneClicked)
END_MESSAGE_MAP()



///////////////////////////////////////////////////////////////////////////////
splash_screen::splash_screen(BOOL AutoClose)
{
    mAutoClose = AutoClose;
    m_dpi = DEFAULT_DPI_96;
    memset(date_built, 0, DATE_STRING_SIZE);
}

///////////////////////////////////////////////////////////////////////////////
BOOL splash_screen::PreCreateWindow(CREATESTRUCT& cs)
{
	if( !CWnd::PreCreateWindow(cs) )
		return FALSE;
	// TODO: Modify the Window class or styles here by modifying
	//  the CREATESTRUCT cs

	return TRUE;
}


void splash_screen::ScreenReaderMessage()
{
    CString HelpString = SPLASH_PRODUCT_NAME;
    HelpString += _T(". ");
    CString version;

    version = "Version: ";
    version += studiox_version_string;
    version += _T(". Build Date: ");
    CString date(__DATE__);
    CString month = date.Left(3);
    CString day = date.Mid(4, 2);
    CString year = date.Right(4);

    version  += month + ' ' + day + ' ' + year;
    HelpString += version;

    SetWindowText(HelpString);
}


///////////////////////////////////////////////////////////////////////////////
int splash_screen::OnCreate(LPCREATESTRUCT lpCreateStruct)
{
    CWnd::OnCreate(lpCreateStruct);
    m_dpi = GetDpiForStudioWindow(GetSafeHwnd());
    CenterWindow();
    ScreenReaderMessage();
    
    if (mAutoClose)
    {
        SetTimer(1, 2000, NULL);
    }
    else
    {
        CRect button_rect;
        GetClientRect(button_rect);
        button_rect.bottom -= MulDiv(10, m_dpi, DEFAULT_DPI_96);
        button_rect.top = button_rect.bottom - MulDiv(20, m_dpi, DEFAULT_DPI_96);
        button_rect.left = max(button_rect.left + MulDiv(220, m_dpi, DEFAULT_DPI_96),
            button_rect.right - MulDiv(205, m_dpi, DEFAULT_DPI_96));
        button_rect.right -= MulDiv(100, m_dpi, DEFAULT_DPI_96);
        CloseButton.Create(_T("Close"), BS_PUSHBUTTON|BS_CENTER|BS_VCENTER|WS_CHILD|WS_VISIBLE, button_rect, this, IDOK);
        CloseButton.SetFont(&NormalFont);
        CloseButton.SetFocus();
    }

    return 0;
}

CString MonthToNumber(CString Month)
{
    if (Month == "Jan")
    {
        return CString("01");
    }
    if (Month == "Feb")
    {
        return CString("02");
    }
    if (Month == "Mar")
    {
        return CString("03");
    }
    if (Month == "Apr")
    {
        return CString("04");
    }
    if (Month == "May")
    {
        return CString("05");
    }
    if (Month == "Jun")
    {
        return CString("06");
    }
    if (Month == "Jul")
    {
        return CString("07");
    }
    if (Month == "Aug")
    {
        return CString("08");
    }
    if (Month == "Sep")
    {
        return CString("09");
    }
    if (Month == "Oct")
    {
        return CString("10");
    }
    if (Month == "Nov")
    {
        return CString("11");
    }
    if (Month == "Dec")
    {
        return CString("12");
    }
    return CString("xx");
}

///////////////////////////////////////////////////////////////////////////////
void splash_screen::OnPaint()
{
    CWnd::OnPaint();
    CDC *dc = GetDC();
    CBitmap map;
    BITMAP bmp;

    if (map.LoadBitmap(IDB_SPLASH_BACKGROUND))
    {
        map.GetBitmap(&bmp);

        CDC dcMemory;
        dcMemory.CreateCompatibleDC(dc);
        dcMemory.SelectObject(&map);

        CRect background_rect;
        GetClientRect(&background_rect);
        dc->StretchBlt(background_rect.left, background_rect.top, background_rect.Width(), background_rect.Height(),
            &dcMemory, 0, 0, bmp.bmWidth, bmp.bmHeight, SRCCOPY);
    }

    CFont *OldFont;

    CString temp;
    CRect rc;
    CRect client;

    int xpos = MulDiv(SPLASH_TEXT_LEFT_96DPI, m_dpi, DEFAULT_DPI_96);
    int ypos = MulDiv(SPLASH_TEXT_TOP_96DPI, m_dpi, DEFAULT_DPI_96);
    int line_height = MulDiv(16, m_dpi, DEFAULT_DPI_96);

    dc->SetTextColor(RGB(248, 208, 40));
    dc->SetBkColor(RGB(0, 0, 0));
    dc->SetBkMode(TRANSPARENT);

    OldFont = dc->SelectObject(&TitleFont);

    GetClientRect(&client);
    rc.SetRect(xpos, ypos, client.right - MulDiv(SPLASH_TEXT_RIGHT_MARGIN_96DPI, m_dpi, DEFAULT_DPI_96),
        ypos + MulDiv(26, m_dpi, DEFAULT_DPI_96));
    dc->DrawText(SPLASH_PRODUCT_NAME, rc, DT_LEFT | DT_SINGLELINE | DT_END_ELLIPSIS);
    ypos += MulDiv(30, m_dpi, DEFAULT_DPI_96);

    temp = "Version ";
    temp += studiox_version_string;
    dc->TextOut(xpos, ypos, temp);
    ypos += MulDiv(30, m_dpi, DEFAULT_DPI_96);
    dc->SelectObject(&TinyFont);

    rc.SetRect(xpos, ypos, client.right - MulDiv(10, m_dpi, DEFAULT_DPI_96), ypos + line_height);
    rc.OffsetRect(0, line_height);

    CString date(__DATE__);
    CString month = date.Left(3);
    CString day = date.Mid(4, 2);
    CString year = date.Right(4);

    temp = "Studio Build Date: ";
    temp += month + '-' + day + '-' + year;
    dc->DrawText(temp, rc, DT_LEFT|DT_SINGLELINE);
    rc.OffsetRect(0, line_height);

    dc->SelectObject(OldFont);
    ReleaseDC(dc);
}

void splash_screen::OnTimer(UINT_PTR nIdEvent)
{
    EndModalLoop(0);
}

void splash_screen::OnDoneClicked()
{
    EndModalLoop(0);
}
