/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.0.10.0-engineering                                  */
/*  Date (dd.mm.yyyy): 14.12.2020   Time (hh:mm): 15:40                        */
/*******************************************************************************/


#ifndef _DEMO_GUIX_SCROLLBAR_DISPLAY_1_RESOURCES_H_
#define _DEMO_GUIX_SCROLLBAR_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_32ARGB
#define DISPLAY_1_X_RESOLUTION 640
#define DISPLAY_1_Y_RESOLUTION 480
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_LIGHT_SLATE_GRAY 29
#define GX_COLOR_ID_GREEN 30
#define GX_COLOR_ID_BLACK 31
#define GX_COLOR_ID_ODD_ROW 32
#define GX_COLOR_ID_OFF_WHITE 33
#define GX_COLOR_ID_TEAL 34
#define GX_COLOR_ID_WHITE 35
#define DISPLAY_1_COLOR_TABLE_SIZE 36

/* Font ID definitions                                                         */

#define GX_FONT_ID_TITLE 4
#define DISPLAY_1_FONT_TABLE_SIZE 5

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_HSCROLL_THUMB 5
#define GX_PIXELMAP_ID_MS_AZURE_LOGO_SMALL 6
#define GX_PIXELMAP_ID_SCROLLABLE_WINDOW_BG 7
#define GX_PIXELMAP_ID_VSCROLL_THUMB 8
#define DISPLAY_1_PIXELMAP_TABLE_SIZE 9

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_4 1
#define GX_STRING_ID_STRING_2 2
#define GX_STRING_ID_STRING_3 3
#define GX_STRING_ID_STRING_5 4
#define DISPLAY_1_STRING_TABLE_SIZE 5

#endif                                       /* sentry                         */
