/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.1.12.0                                              */
/*  Date (dd.mm.yyyy): 25. 8.2022   Time (hh:mm): 18:34                        */
/*******************************************************************************/


#ifndef _DEMO_DISPLAY_RESOLUTION_SECONDARY_RESOURCES_H_
#define _DEMO_DISPLAY_RESOLUTION_SECONDARY_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define SECONDARY 1
#define SECONDARY_COLOR_FORMAT GX_COLOR_FORMAT_8BIT_PALETTE
#define SECONDARY_X_RESOLUTION 641
#define SECONDARY_Y_RESOLUTION 480
#define SECONDARY_THEME_1 0
#define SECONDARY_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define SECONDARY_LANGUAGE_ENGLISH 0
#define SECONDARY_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_SECONDARY_ORANGE 29
#define GX_COLOR_ID_SECONDARY_BLACK 30
#define GX_COLOR_ID_SECONDARY_NEXT_BUTTON_LOWER 31
#define GX_COLOR_ID_SECONDARY_NEXT_BUTTON_UPPER 32
#define GX_COLOR_ID_SECONDARY_WHITE 33
#define SECONDARY_COLOR_TABLE_SIZE 34

/* Font ID definitions                                                         */

#define SECONDARY_FONT_TABLE_SIZE 4

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_SECONDARY_FISH 5
#define GX_PIXELMAP_ID_SECONDARY_I_HISTORY_LG 6
#define GX_PIXELMAP_ID_SECONDARY_I_MEDICATIONSGREEN_LG 7
#define GX_PIXELMAP_ID_SECONDARY_I_MEDICATIONSRED_LG 8
#define GX_PIXELMAP_ID_SECONDARY_I_PATIENTLIST_LG 9
#define GX_PIXELMAP_ID_SECONDARY_RED_APPLE 10
#define GX_PIXELMAP_ID_SECONDARY_SAVE_ICON 11
#define SECONDARY_PIXELMAP_TABLE_SIZE 12

/* String Ids                                                                  */

#define GX_STRING_ID_SECONDARY_STRING_1 1
#define GX_STRING_ID_SECONDARY_STRING_2 2
#define GX_STRING_ID_SECONDARY_STRING_3 3
#define GX_STRING_ID_SECONDARY_STRING_4 4
#define GX_STRING_ID_SECONDARY_STRING_5 5
#define GX_STRING_ID_SECONDARY_STRING_6 6
#define GX_STRING_ID_SECONDARY_STRING_7 7
#define GX_STRING_ID_SECONDARY_STRING_8 8
#define GX_STRING_ID_SECONDARY_STRING_9 9
#define GX_STRING_ID_SECONDARY_STRING_10 10
#define SECONDARY_STRING_TABLE_SIZE 11

#endif                                       /* sentry                         */
