/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  specification file(s). For more information please refer to the Azure RTOS */
/*  GUIX Studio User Guide, or visit our web site at azure.com/rtos            */
/*                                                                             */
/*  GUIX Studio Revision 6.2.1.2                                               */
/*  Date (dd.mm.yyyy):  5. 6.2023   Time (hh:mm): 15:09                        */
/*******************************************************************************/


#define GUIX_STUDIO_GENERATED_FILE
#include <stddef.h>
#include "folder_output_test_MAIN_DISPLAY_resources.h"
#include "folder_output_test_SECONDARY_resources.h"
#include "folder_output_test_specifications.h"

extern GX_WINDOW_ROOT MAIN_DISPLAY_root_window;
extern GX_WINDOW_ROOT SECONDARY_root_window;
GX_CONST GX_STUDIO_WIDGET MAIN_DISPLAY_indicator_screen_define;
extern GX_CONST GX_STUDIO_WIDGET MAIN_DISPLAY_text_screen_define;
extern MAIN_DISPLAY_TEXT_SCREEN_CONTROL_BLOCK MAIN_DISPLAY_text_screen;
GX_WINDOW_PROPERTIES MAIN_DISPLAY_indicator_screen_properties =
{
    0                                        /* wallpaper pixelmap id          */
};
GX_SLIDER_PROPERTIES MAIN_DISPLAY_indicator_screen_slider_properties =
{
    9,                                       /* tickmark count                 */
    0,                                       /* mimimun value                  */
    100,                                     /* maximum value                  */
    50,                                      /* current value                  */
    10,                                      /* increment                      */
    10,                                      /* minimum travel                 */
    10,                                      /* maximum travel                 */
    5,                                       /* needle width                   */
    20,                                      /* needle height                  */
    5,                                       /* needle inset                   */
    2                                        /* needle hotspot                 */
};
GX_SLIDER_PROPERTIES MAIN_DISPLAY_indicator_screen_slider_1_properties =
{
    9,                                       /* tickmark count                 */
    0,                                       /* mimimun value                  */
    100,                                     /* maximum value                  */
    50,                                      /* current value                  */
    10,                                      /* increment                      */
    10,                                      /* minimum travel                 */
    10,                                      /* maximum travel                 */
    20,                                      /* needle width                   */
    5,                                       /* needle height                  */
    5,                                       /* needle inset                   */
    2                                        /* needle hotspot                 */
};
GX_PIXELMAP_SLIDER_PROPERTIES MAIN_DISPLAY_indicator_screen_pixelmap_slider_properties =
{
    0,                                       /* minimum value                  */
    100,                                     /* maximum value                  */
    50,                                      /* current value                  */
    10,                                      /* increment                      */
    10,                                      /* minimum travel                 */
    10,                                      /* maximum travel                 */
    20,                                      /* needle width                   */
    5,                                       /* needle height                  */
    0,                                       /* needle inset                   */
    10,                                      /* needle hotspot                 */
    GX_PIXELMAP_ID_MAIN_DISPLAY_HORIZONTAL_FILL_BKGND, /* lower pixelmap id    */
    0,                                       /* upper pixelmap id              */
    GX_PIXELMAP_ID_MAIN_DISPLAY_I_INDICATOR_HORIZONTAL  /* needle pixelmap id  */
};
GX_PIXELMAP_SLIDER_PROPERTIES MAIN_DISPLAY_indicator_screen_pixelmap_slider_1_properties =
{
    0,                                       /* minimum value                  */
    100,                                     /* maximum value                  */
    50,                                      /* current value                  */
    10,                                      /* increment                      */
    10,                                      /* minimum travel                 */
    10,                                      /* maximum travel                 */
    0,                                       /* needle width                   */
    0,                                       /* needle height                  */
    -2,                                      /* needle inset                   */
    10,                                      /* needle hotspot                 */
    GX_PIXELMAP_ID_MAIN_DISPLAY_I_ORANGEFILL_MIDDLE, /* lower pixelmap id      */
    GX_PIXELMAP_ID_MAIN_DISPLAY_I_EMPTYFILL_MIDDLE, /* upper pixelmap id       */
    GX_PIXELMAP_ID_MAIN_DISPLAY_I_INDICATOR  /* needle pixelmap id             */
};
GX_ICON_PROPERTIES MAIN_DISPLAY_indicator_screen_icon_1_properties =
{
    GX_PIXELMAP_ID_MAIN_DISPLAY_I_EMPTYFILL_TOP, /* normal pixelmap id         */
    0                                        /* selected pixelmap id           */
};
GX_ICON_PROPERTIES MAIN_DISPLAY_indicator_screen_icon_2_properties =
{
    GX_PIXELMAP_ID_MAIN_DISPLAY_I_ORANGEFILL_BOTTOM, /* normal pixelmap id     */
    0                                        /* selected pixelmap id           */
};
GX_PROMPT_PROPERTIES MAIN_DISPLAY_indicator_screen_slider_title_properties =
{
    GX_STRING_ID_MAIN_DISPLAY_STRING_38,     /* string id                      */
    GX_FONT_ID_PROMPT,                       /* font id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_TEXT,                        /* selected text color            */
    GX_COLOR_ID_TEXT                         /* disabled text color            */
};
GX_TEXT_BUTTON_PROPERTIES MAIN_DISPLAY_indicator_screen_next_button_3_properties =
{
    GX_STRING_ID_MAIN_DISPLAY_STRING_36,     /* string id                      */
    GX_FONT_ID_BUTTON,                       /* font id                        */
    GX_COLOR_ID_MAIN_DISPLAY_WHITE,          /* normal text color              */
    GX_COLOR_ID_MAIN_DISPLAY_WHITE,          /* selected text color            */
    GX_COLOR_ID_MAIN_DISPLAY_WHITE           /* disabled text color            */
};
GX_PROGRESS_BAR_INFO MAIN_DISPLAY_indicator_screen_progress_bar_1_properties =
{
    0,                                       /* mimimun value                  */
    100,                                     /* maximum value                  */
    50,                                      /* current value                  */
    GX_FONT_ID_SYSTEM,                       /* font_id                        */
    GX_COLOR_ID_SHINE,                       /* normal text color              */
    GX_COLOR_ID_SHINE,                       /* selected text color            */
    GX_COLOR_ID_SHINE,                       /* disabled text color            */
    0                                        /* fill pixelmap                  */
};
GX_PIXELMAP_SLIDER_PROPERTIES MAIN_DISPLAY_indicator_screen_pixelmap_slider_2_properties =
{
    0,                                       /* minimum value                  */
    100,                                     /* maximum value                  */
    80,                                      /* current value                  */
    10,                                      /* increment                      */
    10,                                      /* minimum travel                 */
    10,                                      /* maximum travel                 */
    0,                                       /* needle width                   */
    20,                                      /* needle height                  */
    4,                                       /* needle inset                   */
    10,                                      /* needle hotspot                 */
    GX_PIXELMAP_ID_MAIN_DISPLAY_I_ORANGEFILL_MIDDLE_HORIZONTAL, /* lower pixelmap id */
    GX_PIXELMAP_ID_MAIN_DISPLAY_I_EMPTYFILL_MIDDLE_HORIZONTAL, /* upper pixelmap id */
    GX_PIXELMAP_ID_MAIN_DISPLAY_I_INDICATOR_HORIZONTAL  /* needle pixelmap id  */
};
GX_RADIAL_PROGRESS_BAR_INFO MAIN_DISPLAY_indicator_screen_radial_progress_bar_properties =
{
    414,                                     /* xcenter                        */
    311,                                     /* ycenter                        */
    23,                                      /* radius                         */
    -80,                                     /* current val                    */
    90,                                      /* anchor val                     */
    GX_FONT_ID_SYSTEM,                       /* font_id                        */
    GX_COLOR_ID_TEXT,                        /* normal text color              */
    GX_COLOR_ID_SELECTED_TEXT,               /* selected text color            */
    GX_COLOR_ID_TEXT,                        /* disabled text color            */
    8,                                       /* normal brush width             */
    8,                                       /* selected brush width           */
    GX_COLOR_ID_SLIDER_NEEDLE_FILL,          /* normal brush color             */
    GX_COLOR_ID_SELECTED_FILL,               /* selected brush color           */
};

GX_CONST GX_STUDIO_WIDGET MAIN_DISPLAY_indicator_screen_radial_progress_bar_define =
{
    "radial_progress_bar",
    GX_TYPE_RADIAL_PROGRESS_BAR,             /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_DYNAMICALLY_ALLOCATED|GX_STYLE_PROGRESS_PERCENT|GX_STYLE_PROGRESS_TEXT_DRAW|GX_STYLE_RADIAL_PROGRESS_ALIAS|GX_STYLE_RADIAL_PROGRESS_ROUND,   /* style flags */
    0,                                       /* status flags                   */
    sizeof(GX_RADIAL_PROGRESS_BAR),          /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_radial_progress_bar_create,     /* create function               */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {387, 284, 441, 338},                    /* widget size                    */
    GX_NULL,                                 /* no next widget                 */
    GX_NULL,                                 /* no child widgets               */ 
    0,                                       /* runtime control block          */
    (void *) &MAIN_DISPLAY_indicator_screen_radial_progress_bar_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET MAIN_DISPLAY_indicator_screen_pixelmap_slider_2_define =
{
    "pixelmap_slider_2",
    GX_TYPE_PIXELMAP_SLIDER,                 /* widget type                    */
    ID_PIXELMAP_SLIDER1,                     /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_DYNAMICALLY_ALLOCATED|GX_STYLE_TILE_BACKGROUND,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_SLIDER),              /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_WIDGET_FILL,                 /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_pixelmap_slider_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {171, 289, 331, 326},                    /* widget size                    */
    &MAIN_DISPLAY_indicator_screen_radial_progress_bar_define, /* next widget definition */
    GX_NULL,                                 /* no child widgets               */ 
    0,                                       /* runtime control block          */
    (void *) &MAIN_DISPLAY_indicator_screen_pixelmap_slider_2_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET MAIN_DISPLAY_indicator_screen_progress_bar_1_define =
{
    "progress_bar_1",
    GX_TYPE_PROGRESS_BAR,                    /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_DYNAMICALLY_ALLOCATED|GX_STYLE_PROGRESS_PERCENT|GX_STYLE_PROGRESS_TEXT_DRAW,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROGRESS_BAR),                 /* control block size             */
    GX_COLOR_ID_SHADOW,                      /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_SHADOW,                      /* disabled color id              */
    gx_studio_progress_bar_create,           /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {276, 225, 441, 263},                    /* widget size                    */
    &MAIN_DISPLAY_indicator_screen_pixelmap_slider_2_define, /* next widget definition */
    GX_NULL,                                 /* no child widgets               */ 
    0,                                       /* runtime control block          */
    (void *) &MAIN_DISPLAY_indicator_screen_progress_bar_1_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET MAIN_DISPLAY_indicator_screen_next_button_3_define =
{
    "next_button_3",
    GX_TYPE_TEXT_BUTTON,                     /* widget type                    */
    IDB_NEXT,                                /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_ENABLED|GX_STYLE_DYNAMICALLY_ALLOCATED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_TEXT_BUTTON),                  /* control block size             */
    GX_COLOR_ID_MAIN_DISPLAY_NEXT_BUTTON_LOWER,     /* normal color id         */
    GX_COLOR_ID_MAIN_DISPLAY_NEXT_BUTTON_UPPER,     /* selected color id       */
    GX_COLOR_ID_MAIN_DISPLAY_NEXT_BUTTON_LOWER,     /* disabled color id       */
    gx_studio_text_button_create,            /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {375, 351, 454, 378},                    /* widget size                    */
    &MAIN_DISPLAY_indicator_screen_progress_bar_1_define, /* next widget definition */
    GX_NULL,                                 /* no child widgets               */ 
    0,                                       /* runtime control block          */
    (void *) &MAIN_DISPLAY_indicator_screen_next_button_3_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET MAIN_DISPLAY_indicator_screen_slider_title_define =
{
    "slider_title",
    GX_TYPE_PROMPT,                          /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_DYNAMICALLY_ALLOCATED|GX_STYLE_TEXT_CENTER,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PROMPT),                       /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_prompt_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {235, 68, 372, 91},                      /* widget size                    */
    &MAIN_DISPLAY_indicator_screen_next_button_3_define, /* next widget definition */
    GX_NULL,                                 /* no child widgets               */ 
    0,                                       /* runtime control block          */
    (void *) &MAIN_DISPLAY_indicator_screen_slider_title_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET MAIN_DISPLAY_indicator_screen_icon_2_define =
{
    "icon_2",
    GX_TYPE_ICON,                            /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED|GX_STYLE_DYNAMICALLY_ALLOCATED|GX_STYLE_HALIGN_LEFT|GX_STYLE_VALIGN_TOP,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON),                         /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_icon_create,                   /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {163, 262, 184, 271},                    /* widget size                    */
    &MAIN_DISPLAY_indicator_screen_slider_title_define, /* next widget definition */
    GX_NULL,                                 /* no child widgets               */ 
    0,                                       /* runtime control block          */
    (void *) &MAIN_DISPLAY_indicator_screen_icon_2_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET MAIN_DISPLAY_indicator_screen_icon_1_define =
{
    "icon_1",
    GX_TYPE_ICON,                            /* widget type                    */
    GX_ID_NONE,                              /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_NONE|GX_STYLE_ENABLED|GX_STYLE_DYNAMICALLY_ALLOCATED|GX_STYLE_HALIGN_LEFT|GX_STYLE_VALIGN_TOP,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_ICON),                         /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_SELECTED_FILL,               /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_icon_create,                   /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {163, 134, 184, 143},                    /* widget size                    */
    &MAIN_DISPLAY_indicator_screen_icon_2_define, /* next widget definition    */
    GX_NULL,                                 /* no child widgets               */ 
    0,                                       /* runtime control block          */
    (void *) &MAIN_DISPLAY_indicator_screen_icon_1_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET MAIN_DISPLAY_indicator_screen_pixelmap_slider_1_define =
{
    "pixelmap_slider_1",
    GX_TYPE_PIXELMAP_SLIDER,                 /* widget type                    */
    ID_PIXELMAP_SLIDER1,                     /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_DYNAMICALLY_ALLOCATED|GX_STYLE_SLIDER_VERTICAL|GX_STYLE_TILE_BACKGROUND,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_SLIDER),              /* control block size             */
    GX_COLOR_ID_WIDGET_FILL,                 /* normal color id                */
    GX_COLOR_ID_WIDGET_FILL,                 /* selected color id              */
    GX_COLOR_ID_WIDGET_FILL,                 /* disabled color id              */
    gx_studio_pixelmap_slider_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {160, 144, 188, 264},                    /* widget size                    */
    &MAIN_DISPLAY_indicator_screen_icon_1_define, /* next widget definition    */
    GX_NULL,                                 /* no child widgets               */ 
    0,                                       /* runtime control block          */
    (void *) &MAIN_DISPLAY_indicator_screen_pixelmap_slider_1_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET MAIN_DISPLAY_indicator_screen_pixelmap_slider_define =
{
    "pixelmap_slider",
    GX_TYPE_PIXELMAP_SLIDER,                 /* widget type                    */
    ID_PIXELMAP_SLIDER_H,                    /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_TRANSPARENT|GX_STYLE_ENABLED|GX_STYLE_DYNAMICALLY_ALLOCATED,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_PIXELMAP_SLIDER),              /* control block size             */
    GX_COLOR_ID_BTN_LOWER,                   /* normal color id                */
    GX_COLOR_ID_BTN_LOWER,                   /* selected color id              */
    GX_COLOR_ID_BTN_LOWER,                   /* disabled color id              */
    gx_studio_pixelmap_slider_create,        /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {283, 185, 426, 206},                    /* widget size                    */
    &MAIN_DISPLAY_indicator_screen_pixelmap_slider_1_define, /* next widget definition */
    GX_NULL,                                 /* no child widgets               */ 
    0,                                       /* runtime control block          */
    (void *) &MAIN_DISPLAY_indicator_screen_pixelmap_slider_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET MAIN_DISPLAY_indicator_screen_slider_1_define =
{
    "slider_1",
    GX_TYPE_SLIDER,                          /* widget type                    */
    ID_SLIDER_1,                             /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RECESSED|GX_STYLE_ENABLED|GX_STYLE_DYNAMICALLY_ALLOCATED|GX_STYLE_SHOW_NEEDLE|GX_STYLE_SHOW_TICKMARKS|GX_STYLE_SLIDER_VERTICAL,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_SLIDER),                       /* control block size             */
    GX_COLOR_ID_BTN_UPPER,                   /* normal color id                */
    GX_COLOR_ID_BTN_UPPER,                   /* selected color id              */
    GX_COLOR_ID_BTN_UPPER,                   /* disabled color id              */
    gx_studio_slider_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {207, 133, 240, 272},                    /* widget size                    */
    &MAIN_DISPLAY_indicator_screen_pixelmap_slider_define, /* next widget definition */
    GX_NULL,                                 /* no child widgets               */ 
    0,                                       /* runtime control block          */
    (void *) &MAIN_DISPLAY_indicator_screen_slider_1_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET MAIN_DISPLAY_indicator_screen_slider_define =
{
    "slider",
    GX_TYPE_SLIDER,                          /* widget type                    */
    ID_SLIDER_HORIZONTAL,                    /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_RAISED|GX_STYLE_ENABLED|GX_STYLE_DYNAMICALLY_ALLOCATED|GX_STYLE_SHOW_NEEDLE|GX_STYLE_SHOW_TICKMARKS,   /* style flags */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(GX_SLIDER),                       /* control block size             */
    GX_COLOR_ID_MAIN_DISPLAY_ORANGE,         /* normal color id                */
    GX_COLOR_ID_MAIN_DISPLAY_ORANGE,         /* selected color id              */
    GX_COLOR_ID_MAIN_DISPLAY_ORANGE,         /* disabled color id              */
    gx_studio_slider_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    GX_NULL,                                 /* event function override        */
    {263, 130, 446, 166},                    /* widget size                    */
    &MAIN_DISPLAY_indicator_screen_slider_1_define, /* next widget definition  */
    GX_NULL,                                 /* no child widgets               */ 
    0,                                       /* runtime control block          */
    (void *) &MAIN_DISPLAY_indicator_screen_slider_properties /* extended properties */
};

GX_STUDIO_ACTION MAIN_DISPLAY_indicator_screen__idb_next_gx_event_clicked_actions[2] = {
    {GX_ACTION_TYPE_TOGGLE, 0, &MAIN_DISPLAY_root_window, &MAIN_DISPLAY_text_screen, GX_NULL},
    {0, 0, GX_NULL, GX_NULL, GX_NULL}
};

static GX_STUDIO_EVENT_ENTRY gx_studio_MAIN_DISPLAY_indicator_screen_event_table[] = {
    {GX_SIGNAL(IDB_NEXT, GX_EVENT_CLICKED), 0, MAIN_DISPLAY_indicator_screen__idb_next_gx_event_clicked_actions},
    {0, 0, GX_NULL}
};

GX_STUDIO_EVENT_PROCESS MAIN_DISPLAY_indicator_screen_event_chain = {gx_studio_MAIN_DISPLAY_indicator_screen_event_table, (UINT (*)(GX_WIDGET *, GX_EVENT *))gx_window_event_process};
static UINT gx_studio_MAIN_DISPLAY_indicator_screen_event_process(GX_WIDGET *target, GX_EVENT *event_ptr)
{
    return (gx_studio_auto_event_handler(target, event_ptr, &MAIN_DISPLAY_indicator_screen_event_chain));
}


GX_CONST GX_STUDIO_WIDGET MAIN_DISPLAY_indicator_screen_define =
{
    "MAIN_DISPLAY_indicator_screen",
    GX_TYPE_WINDOW,                          /* widget type                    */
    ID_INDICATOR_SCREEN,                     /* widget id                      */
    #if defined(GX_WIDGET_USER_DATA)
    0,                                       /* user data                      */
    #endif
    GX_STYLE_BORDER_THIN|GX_STYLE_DYNAMICALLY_ALLOCATED,   /* style flags      */
    GX_STATUS_ACCEPTS_FOCUS,                 /* status flags                   */
    sizeof(MAIN_DISPLAY_INDICATOR_SCREEN_CONTROL_BLOCK), /* control block size */
    GX_COLOR_ID_WINDOW_FILL,                 /* normal color id                */
    GX_COLOR_ID_WINDOW_FILL,                 /* selected color id              */
    GX_COLOR_ID_WINDOW_FILL,                 /* disabled color id              */
    gx_studio_window_create,                 /* create function                */
    GX_NULL,                                 /* drawing function override      */
    (UINT (*)(GX_WIDGET *, GX_EVENT *)) gx_studio_MAIN_DISPLAY_indicator_screen_event_process, /* event function override */
    {146, 53, 465, 386},                     /* widget size                    */
    GX_NULL,                                 /* next widget                    */
    &MAIN_DISPLAY_indicator_screen_slider_define, /* child widget              */
    0,                                       /* control block                  */
    (void *) &MAIN_DISPLAY_indicator_screen_properties /* extended properties  */
};
#undef GUIX_STUDIO_GENERATED_FILE
