/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.1.12.0                                              */
/*  Date (dd.mm.yyyy): 25. 8.2022   Time (hh:mm): 18:35                        */
/*******************************************************************************/


#ifndef _GLYPH_DRAW_8BPP_SCREEN_TEXT_COLORS_16_DISPLAY_1_RESOURCES_H_
#define _GLYPH_DRAW_8BPP_SCREEN_TEXT_COLORS_16_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_8BIT_PALETTE
#define DISPLAY_1_X_RESOLUTION 640
#define DISPLAY_1_Y_RESOLUTION 480
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define DISPLAY_1_COLOR_TABLE_SIZE 29

/* Font ID definitions                                                         */

#define GX_FONT_ID_CHINESE_4BIT 4
#define GX_FONT_ID_CHINESE_1BIT 5
#define DISPLAY_1_FONT_TABLE_SIZE 6

/* Pixelmap ID definitions                                                     */

#define DISPLAY_1_PIXELMAP_TABLE_SIZE 5

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_SYMBLE 1
#define GX_STRING_ID_STRING_CHARACTER 2
#define GX_STRING_ID_STRING_4BPP 3
#define GX_STRING_ID_STRING_1BPP 4
#define GX_STRING_ID_STRING_7 5
#define GX_STRING_ID_STRING_8 6
#define GX_STRING_ID_STRING_9 7
#define GX_STRING_ID_STRING_5 8
#define GX_STRING_ID_STRING_1 9
#define GX_STRING_ID_STRING_2 10
#define GX_STRING_ID_STRING_4 11
#define DISPLAY_1_STRING_TABLE_SIZE 12

#endif                                       /* sentry                         */
