/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.2.1.2                                               */
/*  Date (dd.mm.yyyy):  5. 6.2023   Time (hh:mm): 15:08                        */
/*******************************************************************************/


#include "gx_api.h"
#include "binres_theme_static_language_resources.h"

/* Color Table                                                                 */


/* Font Table                                                                  */


/* Pixelmap data definitions                                                   */


/* Pixelmap Table                                                              */



/* String values                                                               */

GX_CONST GX_UBYTE main_display_STRING_12_English[] = "theme 1";
GX_CONST GX_UBYTE main_display_STRING_13_English[] = "theme 2";
GX_CONST GX_UBYTE main_display_STRING_17_English[] = "Languages";
GX_CONST GX_UBYTE main_display_STRING_1_English[] = "English";
GX_CONST GX_UBYTE main_display_STRING_22_English[] = "Button";
GX_CONST GX_UBYTE main_display_STRING_3_English[] = "Spanish";
GX_CONST GX_UBYTE main_display_STRING_11_English[] = "Themes";
GX_CONST GX_UBYTE main_display_STRING_12_Spanish[] = "temas 1";
GX_CONST GX_UBYTE main_display_STRING_13_Spanish[] = "temas 2";
GX_CONST GX_UBYTE main_display_STRING_17_Spanish[] = "Idiomas";
GX_CONST GX_UBYTE main_display_STRING_1_Spanish[] = {0x49, 0x6e, 0x67, 0x6c, 0xc3, 0xa9, 0x73, 0x00};
GX_CONST GX_UBYTE main_display_STRING_22_Spanish[] = {0x42, 0x6f, 0x74, 0xc3, 0xb3, 0x6e, 0x00};
GX_CONST GX_UBYTE main_display_STRING_3_Spanish[] = {0x45, 0x73, 0x70, 0x61, 0xc3, 0xb1, 0x6f, 0x6c, 0x00};
GX_CONST GX_UBYTE main_display_STRING_11_Spanish[] = "temas";

/* String Table for main_display language English                              */

GX_CONST GX_STRING main_display_English_string_table[8] =
{
    {GX_NULL, 0},
    {(GX_CONST GX_CHAR *)main_display_STRING_12_English, sizeof(main_display_STRING_12_English) - 1},
    {(GX_CONST GX_CHAR *)main_display_STRING_13_English, sizeof(main_display_STRING_13_English) - 1},
    {(GX_CONST GX_CHAR *)main_display_STRING_17_English, sizeof(main_display_STRING_17_English) - 1},
    {(GX_CONST GX_CHAR *)main_display_STRING_1_English, sizeof(main_display_STRING_1_English) - 1},
    {(GX_CONST GX_CHAR *)main_display_STRING_22_English, sizeof(main_display_STRING_22_English) - 1},
    {(GX_CONST GX_CHAR *)main_display_STRING_3_English, sizeof(main_display_STRING_3_English) - 1},
    {(GX_CONST GX_CHAR *)main_display_STRING_11_English, sizeof(main_display_STRING_11_English) - 1}
};

/* String Table for main_display language Spanish                              */

GX_CONST GX_STRING main_display_Spanish_string_table[8] =
{
    {GX_NULL, 0},
    {(GX_CONST GX_CHAR *)main_display_STRING_12_Spanish, sizeof(main_display_STRING_12_Spanish) - 1},
    {(GX_CONST GX_CHAR *)main_display_STRING_13_Spanish, sizeof(main_display_STRING_13_Spanish) - 1},
    {(GX_CONST GX_CHAR *)main_display_STRING_17_Spanish, sizeof(main_display_STRING_17_Spanish) - 1},
    {(GX_CONST GX_CHAR *)main_display_STRING_1_Spanish, sizeof(main_display_STRING_1_Spanish) - 1},
    {(GX_CONST GX_CHAR *)main_display_STRING_22_Spanish, sizeof(main_display_STRING_22_Spanish) - 1},
    {(GX_CONST GX_CHAR *)main_display_STRING_3_Spanish, sizeof(main_display_STRING_3_Spanish) - 1},
    {(GX_CONST GX_CHAR *)main_display_STRING_11_Spanish, sizeof(main_display_STRING_11_Spanish) - 1}
};

/*  Language Table                                                             */


GX_CONST GX_STRING *main_display_language_table[2] = 
{
    main_display_English_string_table,
    main_display_Spanish_string_table,
};
