/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.1.12.0                                              */
/*  Date (dd.mm.yyyy): 25. 8.2022   Time (hh:mm): 18:28                        */
/*******************************************************************************/


#ifndef _ALL_WIDGETS_8BPP_MAIN_DISPLAY_RESOURCES_H_
#define _ALL_WIDGETS_8BPP_MAIN_DISPLAY_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define MAIN_DISPLAY 0
#define MAIN_DISPLAY_COLOR_FORMAT GX_COLOR_FORMAT_8BIT_PALETTE
#define MAIN_DISPLAY_X_RESOLUTION 640
#define MAIN_DISPLAY_Y_RESOLUTION 480
#define MAIN_DISPLAY_THEME_1 0
#define MAIN_DISPLAY_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define MAIN_DISPLAY_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_ORANGE 29
#define GX_COLOR_ID_BLACK 30
#define GX_COLOR_ID_BLUE 31
#define GX_COLOR_ID_WHITE 32
#define GX_COLOR_ID_NEXT_BUTTON_UPPER 33
#define GX_COLOR_ID_NEXT_BUTTON_LOWER 34
#define GX_COLOR_ID_GRAY 35
#define MAIN_DISPLAY_COLOR_TABLE_SIZE 36

/* Font ID definitions                                                         */

#define GX_FONT_ID_NORMAL_FONT 4
#define GX_FONT_ID_SELECTED_FONT 5
#define MAIN_DISPLAY_FONT_TABLE_SIZE 6

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_BLACK_PAUSE 5
#define GX_PIXELMAP_ID_BUTTON_DISABLED 6
#define GX_PIXELMAP_ID_COLLAPSE 7
#define GX_PIXELMAP_ID_EXPAND 8
#define GX_PIXELMAP_ID_FILL 9
#define GX_PIXELMAP_ID_FISH 10
#define GX_PIXELMAP_ID_HORIZONTAL_FILL_BKGND 11
#define GX_PIXELMAP_ID_I_EMPTYFILL_MIDDLE 12
#define GX_PIXELMAP_ID_I_EMPTYFILL_MIDDLE_HORIZONTAL 13
#define GX_PIXELMAP_ID_I_EMPTYFILL_RIGHT 14
#define GX_PIXELMAP_ID_I_EMPTYFILL_TOP 15
#define GX_PIXELMAP_ID_I_HISTORY_LG 16
#define GX_PIXELMAP_ID_I_INDICATOR 17
#define GX_PIXELMAP_ID_I_INDICATOR_HORIZONTAL 18
#define GX_PIXELMAP_ID_I_MEDICATIONSGREEN_LG 19
#define GX_PIXELMAP_ID_I_MEDICATIONSRED_LG 20
#define GX_PIXELMAP_ID_I_ORANGEFILL_BOTTOM 21
#define GX_PIXELMAP_ID_I_ORANGEFILL_LEFT 22
#define GX_PIXELMAP_ID_I_ORANGEFILL_MIDDLE 23
#define GX_PIXELMAP_ID_I_ORANGEFILL_MIDDLE_HORIZONTAL 24
#define GX_PIXELMAP_ID_I_PATIENTLIST_LG 25
#define GX_PIXELMAP_ID_ORANGE_BUTTON 26
#define GX_PIXELMAP_ID_ORANGE_BUTTON_PRESSED 27
#define GX_PIXELMAP_ID_ROTATE_APPLE 28
#define GX_PIXELMAP_ID_ROTATE_FISH 29
#define GX_PIXELMAP_ID_ROTATE_FOOT 30
#define GX_PIXELMAP_ID_SAVE_ICON 31
#define GX_PIXELMAP_ID_SCROLL_WHEEL_SELECTED_BG 32
#define GX_PIXELMAP_ID_TFIELD_FILL_SMALL 33
#define GX_PIXELMAP_ID_TFIELD_LEFT_SMALL 34
#define GX_PIXELMAP_ID_TFIELD_RIGHT_SMALL 35
#define MAIN_DISPLAY_PIXELMAP_TABLE_SIZE 36

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_1 1
#define GX_STRING_ID_STRING_2 2
#define GX_STRING_ID_STRING_3 3
#define GX_STRING_ID_STRING_4 4
#define GX_STRING_ID_STRING_5 5
#define GX_STRING_ID_STRING_6 6
#define GX_STRING_ID_STRING_7 7
#define GX_STRING_ID_STRING_8 8
#define GX_STRING_ID_STRING_9 9
#define GX_STRING_ID_STRING_10 10
#define GX_STRING_ID_STRING_11 11
#define GX_STRING_ID_STRING_12 12
#define GX_STRING_ID_STRING_13 13
#define GX_STRING_ID_STRING_14 14
#define GX_STRING_ID_STRING_15 15
#define GX_STRING_ID_STRING_16 16
#define GX_STRING_ID_STRING_17 17
#define GX_STRING_ID_STRING_18 18
#define GX_STRING_ID_STRING_19 19
#define GX_STRING_ID_STRING_20 20
#define GX_STRING_ID_STRING_21 21
#define GX_STRING_ID_STRING_22 22
#define GX_STRING_ID_STRING_23 23
#define GX_STRING_ID_STRING_24 24
#define GX_STRING_ID_STRING_25 25
#define GX_STRING_ID_STRING_26 26
#define GX_STRING_ID_STRING_27 27
#define GX_STRING_ID_STRING_28 28
#define GX_STRING_ID_STRING_29 29
#define GX_STRING_ID_STRING_30 30
#define GX_STRING_ID_STRING_31 31
#define GX_STRING_ID_STRING_32 32
#define GX_STRING_ID_STRING_33 33
#define GX_STRING_ID_STRING_34 34
#define GX_STRING_ID_STRING_35 35
#define GX_STRING_ID_STRING_36 36
#define GX_STRING_ID_STRING_37 37
#define GX_STRING_ID_STRING_38 38
#define GX_STRING_ID_STRING_48 39
#define GX_STRING_ID_STRING_50 40
#define GX_STRING_ID_STRING_51 41
#define GX_STRING_ID_STRING_47 42
#define GX_STRING_ID_STRING_53 43
#define GX_STRING_ID_MENU_1 44
#define GX_STRING_ID_ITEM_1 45
#define GX_STRING_ID_MULTI_LEVEL_ACCORDION_DESCRITION 46
#define GX_STRING_ID_MENU_3 47
#define GX_STRING_ID_STRING_54 48
#define GX_STRING_ID_ITEM_2 49
#define GX_STRING_ID_STRING_39 50
#define GX_STRING_ID_STRING_52 51
#define GX_STRING_ID_STRING_58 52
#define GX_STRING_ID_STRING_57 53
#define GX_STRING_ID_STRING_66 54
#define GX_STRING_ID_STRING_67 55
#define GX_STRING_ID_STRING_68 56
#define GX_STRING_ID_STRING_65 57
#define GX_STRING_ID_STRING_59 58
#define GX_STRING_ID_STRING_64 59
#define GX_STRING_ID_STRING_69 60
#define GX_STRING_ID_STRING_70 61
#define GX_STRING_ID_STRING_72 62
#define GX_STRING_ID_STRING_83 63
#define GX_STRING_ID_STRING_73 64
#define GX_STRING_ID_STRING_74 65
#define GX_STRING_ID_STRING_75 66
#define GX_STRING_ID_STRING_84 67
#define GX_STRING_ID_STRING_86 68
#define GX_STRING_ID_STRING_85 69
#define GX_STRING_ID_STRING_87 70
#define GX_STRING_ID_STRING_88 71
#define GX_STRING_ID_STRING_76 72
#define GX_STRING_ID_STRING_77 73
#define GX_STRING_ID_STRING_71 74
#define GX_STRING_ID_STRING_78 75
#define GX_STRING_ID_STRING_79 76
#define GX_STRING_ID_STRING_80 77
#define GX_STRING_ID_STRING_81 78
#define GX_STRING_ID_STRING_82 79
#define GX_STRING_ID_STRING_40 80
#define GX_STRING_ID_STRING_41 81
#define GX_STRING_ID_STRING_42 82
#define GX_STRING_ID_STRING_43 83
#define GX_STRING_ID_STRING_44 84
#define GX_STRING_ID_STRING_45 85
#define GX_STRING_ID_STRING_46 86
#define GX_STRING_ID_STRING_49 87
#define GX_STRING_ID_STRING_55 88
#define GX_STRING_ID_STRING_56 89
#define GX_STRING_ID_STRING_60 90
#define GX_STRING_ID_STRING_61 91
#define GX_STRING_ID_STRING_39_1 92
#define GX_STRING_ID_STRING_40_1 93
#define GX_STRING_ID_STRING_41_1 94
#define GX_STRING_ID_STRING_42_1 95
#define GX_STRING_ID_STRING_43_1 96
#define GX_STRING_ID_STRING_44_1 97
#define MAIN_DISPLAY_STRING_TABLE_SIZE 98

#endif                                       /* sentry                         */
