/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* Regression test for reading one byte past the end of a GX_STRING when it
 * ends with a carriage return.
 *
 * A GX_STRING carries its own length and need not be NUL terminated, and
 * _gx_multi_line_text_view_text_set_ext() stores the caller's string verbatim
 * unless GX_STYLE_TEXT_COPY is set. When the last byte of such a string is a
 * carriage return, _gx_multi_line_text_view_display_info_get() examined the
 * byte after it to decide whether the terminator was "\r" or "\r\n". That byte
 * lies outside the caller's buffer.
 *
 * Beyond the read itself, if the byte happened to be a line feed the function
 * reported a two-byte terminator for a one-byte remainder, so callers advanced
 * their index past gx_string_length -- and
 * _gx_multi_line_text_view_string_total_rows_compute() then read
 * string.gx_string_ptr[index - 1] one byte past the end as well, and could add
 * a row that is not in the text.
 *
 * The fixtures below place a line feed immediately after the string under test
 * but outside the length the widget is given, so the over-read is observable
 * without a sanitizer: the old code counts the out-of-bounds byte, the fixed
 * code does not.
 *
 * Tests:
 *   1. Range ending on a carriage return, line feed just past the end: the
 *      terminator counts as one byte, not two.
 *   2. Control -- the same buffer with the line feed inside the range: two.
 *   3. Control -- carriage return followed by ordinary text: one.
 *   4. _gx_multi_line_text_input_new_line_character_get() gives a one-byte
 *      terminator for text ending in a lone carriage return, and two bytes for
 *      a "\r\n" pair.
 */

#include <stdio.h>
#include "tx_api.h"
#include "gx_api.h"
#include "gx_system.h"
#include "gx_widget.h"
#include "gx_multi_line_text_view.h"
#include "gx_validation_utility.h"

TEST_PARAM test_parameter = {
    "guix_ml_text_line_terminator_bounds_no_output",
    0, 0, 0, 0
};

int main(int argc, char **argv)
{
    tx_kernel_enter();
    return 0;
}

static VOID control_thread_entry(ULONG input);

VOID tx_application_define(void *first_unused_memory)
{
    gx_validation_control_thread_create(control_thread_entry);
    gx_validation_application_define(first_unused_memory);
    gx_validation_watchdog_create(100);
}

#ifdef WIN32
#undef WIN32
#endif

#include "gx_validation_wrapper.h"
#include "demo_guix_all_widgets.c"

static VOID control_thread_entry(ULONG input)
{
int                       failed_tests = 0;
GX_MULTI_LINE_TEXT_VIEW   text_view;
GX_MULTI_LINE_TEXT_INPUT *ml_input = &text_screen.text_screen_text_input_2;
GX_RECTANGLE              size;
GX_MULTI_LINE_TEXT_INFO   info;
GX_STRING                 string;

/* The string under test is the first three bytes, "AB\r". The line feed is
   deliberately present in the buffer but outside that length. */
GX_CONST GX_CHAR          cr_then_lf[] = "AB\r\n";
GX_CONST GX_CHAR          cr_then_text[] = "AB\rX";
GX_CONST GX_CHAR          trailing_cr[] = "A\r";
GX_CONST GX_CHAR          trailing_crlf[] = "A\r\n";

    memset(&text_view, 0, sizeof(GX_MULTI_LINE_TEXT_VIEW));
    gx_utility_rectangle_define(&size, 0, 0, 200, 200);
    gx_multi_line_text_view_create(&text_view, "test_terminator", GX_NULL, 0, 0, 0, &size);
    text_view.gx_multi_line_text_view_font_id = GX_FONT_ID_TEXT_INPUT;

    /* Attach the widget to root so the display and font table can be found
       through the parent chain. */
    text_view.gx_widget_parent = (GX_WIDGET *)root;
    text_view.gx_widget_status |= GX_STATUS_VISIBLE;

    /* --- Test 1: carriage return is the last byte of the string --- */
    text_view.gx_multi_line_text_view_text.gx_string_ptr = cr_then_lf;
    text_view.gx_multi_line_text_view_text.gx_string_length = 3;

    _gx_multi_line_text_view_display_info_get(&text_view, 0, 3, &info, 200);

    /* 'A', 'B' and the carriage return: 3. Counting the line feed that follows
       the string would give 4 and advance the caller past its own buffer. */
    EXPECT_EQ(3, (int)info.gx_text_display_number);

    /* --- Test 2: control, the line feed is inside the string --- */
    text_view.gx_multi_line_text_view_text.gx_string_length = 4;

    _gx_multi_line_text_view_display_info_get(&text_view, 0, 4, &info, 200);

    EXPECT_EQ(4, (int)info.gx_text_display_number);

    /* --- Test 3: control, ordinary text follows the carriage return --- */
    text_view.gx_multi_line_text_view_text.gx_string_ptr = cr_then_text;
    text_view.gx_multi_line_text_view_text.gx_string_length = 4;

    _gx_multi_line_text_view_display_info_get(&text_view, 0, 4, &info, 200);

    EXPECT_EQ(3, (int)info.gx_text_display_number);

    /* --- Test 4: the terminator a text input adopts from its text ---
       _gx_multi_line_text_input_text_set_ext() writes a NUL after the copied
       text, so the byte after a trailing carriage return is in bounds here.
       These cases pin that behaviour rather than reproduce a read past the
       end: the same idiom is fixed in that file so it does not depend on an
       invariant established elsewhere. */
    string.gx_string_ptr = trailing_cr;
    string.gx_string_length = sizeof(trailing_cr) - 1;
    EXPECT_EQ(GX_SUCCESS, gx_multi_line_text_input_text_set_ext(ml_input, &string));

    EXPECT_EQ(1, (int)ml_input -> gx_multi_line_text_input_new_line_character_size);
    EXPECT_EQ(GX_KEY_CARRIAGE_RETURN, (int)ml_input -> gx_multi_line_text_input_new_line_character[0]);

    string.gx_string_ptr = trailing_crlf;
    string.gx_string_length = sizeof(trailing_crlf) - 1;
    EXPECT_EQ(GX_SUCCESS, gx_multi_line_text_input_text_set_ext(ml_input, &string));

    EXPECT_EQ(2, (int)ml_input -> gx_multi_line_text_input_new_line_character_size);
    EXPECT_EQ(GX_KEY_CARRIAGE_RETURN, (int)ml_input -> gx_multi_line_text_input_new_line_character[0]);
    EXPECT_EQ(GX_KEY_LINE_FEED, (int)ml_input -> gx_multi_line_text_input_new_line_character[1]);

    if (failed_tests == 0)
    {
        gx_validation_print_test_result(TEST_SUCCESS);
        exit(0);
    }
    else
    {
        gx_validation_print_test_result(TEST_FAIL);
        exit(1);
    }
}
