/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* Regression test for issue #148: draw context stack overflow corruption.
 *
 * When _gx_canvas_drawing_initiate() returns GX_DRAW_NESTING_EXCEEDED the
 * context stack is NOT advanced, so the matching _gx_canvas_drawing_complete()
 * must NOT be called.  Calling it anyway decrements gx_canvas_draw_nesting and
 * advances _gx_system_current_draw_context, corrupting the outer drawing state.
 *
 * Tests:
 *   1. _gx_canvas_drawing_initiate() returns GX_DRAW_NESTING_EXCEEDED at max depth.
 *   2. The overflow leaves gx_canvas_draw_nesting and the context pointer unchanged.
 *   3. Caller regression (_gx_widget_block_move): does not corrupt state at max depth.
 *   4. Full unwind restores gx_canvas_draw_nesting == 0 and context pointer == NULL.
 *   5. The stack is usable again after a full unwind (recovery check).
 */

#include <stdio.h>
#include "tx_api.h"
#include "gx_api.h"
#include "gx_system.h"
#include "gx_widget.h"
#include "gx_validation_utility.h"

TEST_PARAM test_parameter = {
    "guix_canvas_draw_nesting_overflow_no_output",
    0, 0, 0, 0
};

int main(int argc, char **argv)
{
    tx_kernel_enter();
    return 0;
}

static VOID control_thread_entry(ULONG input);

VOID tx_application_define(void *first_unused_memory)
{
    gx_validation_control_thread_create(control_thread_entry);
    gx_validation_application_define(first_unused_memory);
    gx_validation_watchdog_create(100);
}

#ifdef WIN32
#undef WIN32
#endif

#include "gx_validation_wrapper.h"
#include "demo_guix_all_widgets.c"

static VOID control_thread_entry(ULONG input)
{
int              failed_tests = 0;
GX_CANVAS       *canvas;
GX_RECTANGLE     size;
UINT             status;
UINT             i;
GX_UBYTE         expected_nesting;
GX_DRAW_CONTEXT *saved_context_ptr;
GX_RECTANGLE     block;

    canvas = root->gx_window_root_canvas;
    gx_utility_rectangle_define(&size, 0, 0, 639, 479);

    /* Pre-conditions: stack must be clean before the test starts. */
    EXPECT_EQ(0,      (int)canvas->gx_canvas_draw_nesting);
    EXPECT_EQ(GX_NULL, _gx_system_current_draw_context);

    /* Fill the context stack to its maximum depth.  Each call with
       who == GX_NULL on a normal canvas returns GX_NO_VIEWS (the context IS
       pushed), so GX_MAX_CONTEXT_NESTING successful pushes are possible.  */
    for (i = 0; i < GX_MAX_CONTEXT_NESTING; i++)
    {
        status = gx_canvas_drawing_initiate(canvas, GX_NULL, &size);
        EXPECT_EQ(GX_NO_VIEWS, status);
    }

    expected_nesting = GX_MAX_CONTEXT_NESTING;
    EXPECT_EQ(expected_nesting, canvas->gx_canvas_draw_nesting);
    EXPECT_EQ(&_gx_system_draw_context_stack[0], _gx_system_current_draw_context);

    /* Save the "at-max-depth" state for comparison after caller test. */
    saved_context_ptr = _gx_system_current_draw_context;

    /* Test 1: overflow is detected. */
    status = gx_canvas_drawing_initiate(canvas, GX_NULL, &size);
    EXPECT_EQ(GX_DRAW_NESTING_EXCEEDED, status);

    /* Test 2: overflow must not change nesting or context pointer. */
    EXPECT_EQ(expected_nesting, canvas->gx_canvas_draw_nesting);
    EXPECT_EQ(saved_context_ptr, _gx_system_current_draw_context);

    /* Test 3: caller regression — _gx_widget_block_move must not corrupt
       gx_canvas_draw_nesting or _gx_system_current_draw_context when the
       inner _gx_canvas_drawing_initiate() returns GX_DRAW_NESTING_EXCEEDED.

       button_screen is a GX_WINDOW (non-transparent) on the same root canvas,
       so _gx_widget_canvas_get() returns 'canvas' and the initiate call hits
       the overflow path.  The shift (1,1) is well within the widget bounds.  */
    button_screen.gx_widget_status &= ~GX_STATUS_TRANSPARENT;
    gx_utility_rectangle_define(&block,
                                button_screen.gx_widget_size.gx_rectangle_left,
                                button_screen.gx_widget_size.gx_rectangle_top,
                                button_screen.gx_widget_size.gx_rectangle_right,
                                button_screen.gx_widget_size.gx_rectangle_bottom);
    _gx_widget_block_move((GX_WIDGET *)&button_screen, &block, 1, 1);

    /* State must be identical to the saved "at-max-depth" snapshot. */
    EXPECT_EQ(expected_nesting, canvas->gx_canvas_draw_nesting);
    EXPECT_EQ(saved_context_ptr, _gx_system_current_draw_context);

    /* Test 4: unwind all valid contexts — stack must reach zero. */
    for (i = 0; i < GX_MAX_CONTEXT_NESTING; i++)
    {
        gx_canvas_drawing_complete(canvas, GX_FALSE);
    }
    EXPECT_EQ(0,      (int)canvas->gx_canvas_draw_nesting);
    EXPECT_EQ(GX_NULL, _gx_system_current_draw_context);

    /* Test 5: recovery — the stack is fully usable after a complete unwind. */
    status = gx_canvas_drawing_initiate(canvas, GX_NULL, &size);
    EXPECT_EQ(GX_NO_VIEWS, status);
    EXPECT_EQ(1, (int)canvas->gx_canvas_draw_nesting);
    gx_canvas_drawing_complete(canvas, GX_FALSE);
    EXPECT_EQ(0,      (int)canvas->gx_canvas_draw_nesting);
    EXPECT_EQ(GX_NULL, _gx_system_current_draw_context);

    if (failed_tests == 0)
    {
        gx_validation_print_test_result(TEST_SUCCESS);
        exit(0);
    }
    else
    {
        gx_validation_print_test_result(TEST_FAIL);
        exit(1);
    }
}
