/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* Regression test for issue #130: word-wrapping broken for UTF-8 strings.
 *
 * _gx_multi_line_text_view_display_info_get() had a guard
 * `(ch.gx_string_ptr[0] != ' ')` in the overflow condition that prevented
 * the overflow branch from executing when an ASCII space caused overflow.
 * The space was instead appended to gx_text_display_width, making it
 * exceed available_width.
 *
 * Tests:
 *   1. Space at overflow boundary: gx_text_display_width <= available_width.
 *   2. Space at overflow boundary: gx_text_display_number includes the
 *      trailing space (next line does not start with a space).
 *   3. Multiple consecutive spaces at overflow boundary: all trailing spaces
 *      are consumed in gx_text_display_number.
 *   4. Normal word overflow (non-space char): backtrack to last word
 *      boundary still works correctly (no regression).
 */

#include <stdio.h>
#include "tx_api.h"
#include "gx_api.h"
#include "gx_system.h"
#include "gx_widget.h"
#include "gx_multi_line_text_view.h"
#include "gx_validation_utility.h"

TEST_PARAM test_parameter = {
    "guix_ml_text_view_word_wrap_no_output",
    0, 0, 0, 0
};

int main(int argc, char **argv)
{
    tx_kernel_enter();
    return 0;
}

static VOID control_thread_entry(ULONG input);

VOID tx_application_define(void *first_unused_memory)
{
    gx_validation_control_thread_create(control_thread_entry);
    gx_validation_application_define(first_unused_memory);
    gx_validation_watchdog_create(100);
}

#ifdef WIN32
#undef WIN32
#endif

#include "gx_validation_wrapper.h"
#include "demo_guix_all_widgets.c"

static VOID control_thread_entry(ULONG input)
{
int                      failed_tests = 0;
GX_MULTI_LINE_TEXT_VIEW  text_view;
GX_RECTANGLE             size;
GX_MULTI_LINE_TEXT_INFO  info;
GX_FONT                 *font;
GX_VALUE                 a_width;
GX_VALUE                 space_width;
GX_VALUE                 b_width;
GX_VALUE                 avail;
GX_STRING                ch;
GX_CONST GX_CHAR         text1[] = "A B";
GX_CONST GX_CHAR         text2[] = "A  B";
GX_CONST GX_CHAR         text3[] = "AB CD";

    memset(&text_view, 0, sizeof(GX_MULTI_LINE_TEXT_VIEW));
    gx_utility_rectangle_define(&size, 0, 0, 200, 200);
    gx_multi_line_text_view_create(&text_view, "test_word_wrap", GX_NULL, 0, 0, 0, &size);
    text_view.gx_multi_line_text_view_font_id = GX_FONT_ID_TEXT_INPUT;

    /* Attach the widget to root so _gx_widget_canvas_get can find the display
       and font table through the parent chain. */
    text_view.gx_widget_parent = (GX_WIDGET *)root;
    text_view.gx_widget_status |= GX_STATUS_VISIBLE;

    /* Measure individual glyph widths to build font-independent test cases. */
    _gx_widget_font_get((GX_WIDGET *)&text_view, GX_FONT_ID_TEXT_INPUT, &font);
    EXPECT_EQ(1, font != GX_NULL);

    ch.gx_string_ptr = "A"; ch.gx_string_length = 1;
    _gx_system_string_width_get_ext(font, &ch, &a_width);

    ch.gx_string_ptr = " "; ch.gx_string_length = 1;
    _gx_system_string_width_get_ext(font, &ch, &space_width);

    ch.gx_string_ptr = "B"; ch.gx_string_length = 1;
    _gx_system_string_width_get_ext(font, &ch, &b_width);

    EXPECT_EQ(1, a_width > 0);
    EXPECT_EQ(1, space_width > 0);

    /* available_width = a_width + space_width forces the space in "A B" to
       be the character that causes overflow (running_width + space_width
       == available_width >= available_width). */
    avail = (GX_VALUE)(a_width + space_width);

    /* --- Test 1 & 2: single space at overflow boundary ("A B") --- */
    text_view.gx_multi_line_text_view_text.gx_string_ptr = text1;
    text_view.gx_multi_line_text_view_text.gx_string_length = sizeof(text1) - 1;

    _gx_multi_line_text_view_display_info_get(&text_view, 0, sizeof(text1) - 1, &info, avail);

    /* Test 1: display_width must not exceed available_width. */
    EXPECT_EQ(1, info.gx_text_display_width <= (USHORT)avail);

    /* Test 2: display_number must include the trailing space (= 2 bytes:
       'A' and ' ') so the next line starts at 'B'. */
    EXPECT_EQ(2, (int)info.gx_text_display_number);

    /* --- Test 3: multiple consecutive spaces at overflow ("A  B") --- */
    text_view.gx_multi_line_text_view_text.gx_string_ptr = text2;
    text_view.gx_multi_line_text_view_text.gx_string_length = sizeof(text2) - 1;

    _gx_multi_line_text_view_display_info_get(&text_view, 0, sizeof(text2) - 1, &info, avail);

    /* Both spaces must be consumed so the next line starts at 'B'. */
    EXPECT_EQ(3, (int)info.gx_text_display_number);

    /* --- Test 4: non-space char causes overflow ("AB CD") --- */
    /* available_width = a_width + b_width + space_width + 1 ensures the
       space fits (no overflow at space) but 'C' overflows, triggering
       backtrack to after the "AB " word boundary. */
    avail = (GX_VALUE)(a_width + b_width + space_width + 1);

    text_view.gx_multi_line_text_view_text.gx_string_ptr = text3;
    text_view.gx_multi_line_text_view_text.gx_string_length = sizeof(text3) - 1;

    _gx_multi_line_text_view_display_info_get(&text_view, 0, sizeof(text3) - 1, &info, avail);

    /* display_number == 3 means the line contains "AB " (backtracked
       to the word boundary after the space). */
    EXPECT_EQ(3, (int)info.gx_text_display_number);

    /* display_width must also be within available_width. */
    EXPECT_EQ(1, info.gx_text_display_width <= (USHORT)avail);

    if (failed_tests == 0)
    {
        gx_validation_print_test_result(TEST_SUCCESS);
        exit(0);
    }
    else
    {
        gx_validation_print_test_result(TEST_FAIL);
        exit(1);
    }
}
