/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* Glyph range and glyph buffer bounds in the binary resource font loader, in
   the extended Unicode configuration. A 32-bit character code is what lets a
   page declare a span wide enough for the reservation multiply to wrap, so the
   reported chain is only reachable in a build like this one.

   The cases themselves live in gx_validation_binres_glyph_range.h, which each
   font configuration runs in turn.  */

#include <stdio.h>
#include "tx_api.h"
#include "gx_api.h"
#include "gx_validation_utility.h"
#include "gx_system.h"

TEST_PARAM test_parameter = {0};

int main(int argc, char ** argv)
{
    /* Start ThreadX system */
    tx_kernel_enter();
    return(0);
}

static TX_THREAD               Guix_API_Test;
static VOID      control_thread_entry(ULONG);
static ULONG     control_thread_stack[1024];

VOID tx_application_define(void *first_unused_memory)
{
    gx_validation_application_define(first_unused_memory);

    /* Termiante the test if it runs for more than 100 ticks */
    /* This function is not implemented yet. */
    gx_validation_watchdog_create(100);

    tx_thread_create(&Guix_API_Test, "GUIX API Test", control_thread_entry,
                     0, control_thread_stack, sizeof(control_thread_stack),
                     GX_SYSTEM_THREAD_PRIORITY + 1, GX_SYSTEM_THREAD_PRIORITY + 1,
                     TX_NO_TIME_SLICE, TX_AUTO_START);
}

/* Replace the default graphics driver with the validation driver. */
#ifdef win32_graphics_driver_setup_24xrgb
#undef win32_graphics_driver_setup_24xrgb
#endif
#define win32_graphics_driver_setup_24xrgb  gx_validation_graphics_driver_setup_24xrgb

#ifdef WIN32
#undef WIN32
#endif

#include "gx_validation_wrapper.h"
#include "demo_guix_standalone_binres_load_extended_unicode_32bpp.c"
#include "gx_validation_binres_glyph_range.h"

static VOID control_thread_entry(ULONG input)
{
    if (gx_validation_binres_glyph_range_run() == 0)
    {
        printf("Guix Test:   guix_binres_font_glyph_range_ex_unicode_no_output.........................................Success!\n");
        exit(0);
    }
    else
    {
        printf("Guix Test:   guix_binres_font_glyph_range_ex_unicode_no_output..........................................Failed!\n");
        exit(1);
    }
}
