/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* Loads themes by id from a resource that declares two, through an allocator
   that serves a request for zero bytes, as malloc() does, and guards the end
   of every allocation. A theme the resource does not hold must be refused
   before anything is allocated or written. */

#include <stdio.h>
#include <string.h>
#include "tx_api.h"
#include "gx_api.h"
#include "gx_validation_utility.h"
#include "gx_system.h"

TEST_PARAM test_parameter = {0};

int main(int argc, char ** argv)
{
    /* Start ThreadX system */
    tx_kernel_enter();
    return(0);
}

static TX_THREAD               Guix_API_Test;
static VOID      control_thread_entry(ULONG);
static ULONG     control_thread_stack[1024];

VOID tx_application_define(void *first_unused_memory)
{
    gx_validation_application_define(first_unused_memory);

    /* Termiante the test if it runs for more than 100 ticks */
    /* This function is not implemented yet. */
    gx_validation_watchdog_create(100);

    tx_thread_create(&Guix_API_Test, "GUIX API Test", control_thread_entry,
                     0, control_thread_stack, sizeof(control_thread_stack),
                     GX_SYSTEM_THREAD_PRIORITY + 1, GX_SYSTEM_THREAD_PRIORITY + 1,
                     TX_NO_TIME_SLICE, TX_AUTO_START);
}

/* Replace the default graphics driver with the validation driver. */
#ifdef win32_graphics_driver_setup_24xrgb
#undef win32_graphics_driver_setup_24xrgb
#endif
#define win32_graphics_driver_setup_24xrgb  gx_validation_graphics_driver_setup_24xrgb

#ifdef WIN32
#undef WIN32
#endif

#include "gx_validation_wrapper.h"
#include "demo_guix_multi_themes_16bpp.c"

#define GUARD_SIZE 64
#define GUARD_BYTE 0xa5

static INT outstanding_allocations = 0;
static INT guard_failures = 0;

/* Each allocation carries its size in front and guard bytes behind, and a
   request for zero bytes is served rather than refused. */
static VOID *guarded_allocate(ULONG size)
{
GX_UBYTE *memptr;

    memptr = memory_allocate(size + sizeof(ULONG) + GUARD_SIZE);

    if (memptr == GX_NULL)
    {
        return GX_NULL;
    }

    memcpy(memptr, &size, sizeof(ULONG));
    memset(memptr + sizeof(ULONG) + size, GUARD_BYTE, GUARD_SIZE);
    outstanding_allocations++;

    return memptr + sizeof(ULONG);
}

static VOID guarded_free(VOID *mem)
{
GX_UBYTE *memptr = (GX_UBYTE *)mem - sizeof(ULONG);
ULONG     size;
INT       index;

    memcpy(&size, memptr, sizeof(ULONG));

    for (index = 0; index < GUARD_SIZE; index++)
    {
        if (memptr[sizeof(ULONG) + size + index] != GUARD_BYTE)
        {
            guard_failures++;
            break;
        }
    }

    outstanding_allocations--;
    memory_free(memptr);
}

/* Reads a whole file into memory from the pool. */
static GX_UBYTE *test_file_load(GX_CONST GX_CHAR *path)
{
FILE     *p_file;
long      total_length;
GX_UBYTE *address = GX_NULL;

    p_file = fopen(path, "rb");

    if (!p_file)
    {
        printf("Cannot open file:%s\n", path);
        return GX_NULL;
    }

    fseek(p_file, 0, SEEK_END);
    total_length = ftell(p_file);
    fseek(p_file, 0, SEEK_SET);

    if (total_length > 0)
    {
        address = memory_allocate((ULONG)total_length);

        if (address && (fread(address, 1, (size_t)total_length, p_file) != (size_t)total_length))
        {
            memory_free(address);
            address = GX_NULL;
        }
    }

    fclose(p_file);

    return address;
}

static VOID control_thread_entry(ULONG input)
{
int       failed_tests = 0;
GX_THEME *loaded_theme;
INT       theme_id;
INT       invalid_ids[] = {2, 3, 100, 0x7fffffff};
UINT      index;
GX_UBYTE *root;
GX_CHAR   path[512];
INT       path_length;

    /* The loads run with GUIX idle, so that every allocation made while the
       guarded allocator is installed is the loader's. */
    tx_thread_suspend(&_gx_system_thread);

    gx_validation_extract_path(__FILE__, path, &path_length);
    strcpy(path + path_length, "..//..//..//example_internal//multi_themes_16bpp//multi_themes_16bpp_resources.bin");
    root = test_file_load(path);
    EXPECT_EQ(1, (root != GX_NULL) ? 1 : 0);

    gx_system_memory_allocator_set(guarded_allocate, guarded_free);

    /* The two themes the resource holds load. */
    for (theme_id = 0; theme_id < 2; theme_id++)
    {
        loaded_theme = GX_NULL;
        EXPECT_EQ(GX_SUCCESS, gx_binres_theme_load(root, theme_id, &loaded_theme));

        if (loaded_theme)
        {
            guarded_free(loaded_theme);
        }
    }

    /* A theme past the last one is refused, with nothing allocated. */
    for (index = 0; index < sizeof(invalid_ids) / sizeof(invalid_ids[0]); index++)
    {
        loaded_theme = GX_NULL;
        EXPECT_EQ(GX_INVALID_VALUE, gx_binres_theme_load(root, invalid_ids[index], &loaded_theme));
        EXPECT_EQ(GX_NULL, loaded_theme);
        EXPECT_EQ(0, outstanding_allocations);

        if (loaded_theme)
        {
            guarded_free(loaded_theme);
        }
    }

    EXPECT_EQ(0, guard_failures);

    gx_system_memory_allocator_set(memory_allocate, memory_free);
    tx_thread_resume(&_gx_system_thread);

    if(failed_tests == 0)
    {
        printf("Guix Test:   guix_binres_theme_id_bound_no_output............................................Success!\n");
        exit(0);
    }
    else
    {
        printf("Guix Test:   guix_binres_theme_id_bound_no_output.............................................Failed!\n");
        exit(1);
    }
}
