/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.0.0.0                                               */
/*  Date (dd.mm.yyyy):  8. 5.2020   Time (hh:mm): 17:08                        */
/*******************************************************************************/


#ifndef _DEMO_GUIX_INDUSTRIAL_MAIN_DISPLAY_RESOURCES_H_
#define _DEMO_GUIX_INDUSTRIAL_MAIN_DISPLAY_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define MAIN_DISPLAY 0
#define MAIN_DISPLAY_COLOR_FORMAT GX_COLOR_FORMAT_32ARGB
#define MAIN_DISPLAY_X_RESOLUTION 640
#define MAIN_DISPLAY_Y_RESOLUTION 480
#define MAIN_DISPLAY_THEME_1 0
#define MAIN_DISPLAY_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define MAIN_DISPLAY_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_WHITE 29
#define GX_COLOR_ID_BLACK 30
#define GX_COLOR_ID_SILVER_GRAY 31
#define GX_COLOR_ID_DARK_GRAY 32
#define GX_COLOR_ID_LIGHT_GRAY 33
#define GX_COLOR_ID_PROGRESS_BG 34
#define GX_COLOR_ID_GREEN 35
#define GX_COLOR_ID_RADIAL_PROGRESS_BAR_FILL 36
#define MAIN_DISPLAY_COLOR_TABLE_SIZE 37

/* Font ID definitions                                                         */

#define GX_FONT_ID_NORMAL 4
#define GX_FONT_ID_BIG 5
#define GX_FONT_ID_MIDDLE 6
#define GX_FONT_ID_SMALL 7
#define GX_FONT_ID_MIDDLE_45 8
#define GX_FONT_ID_MIDDLE_30 9
#define GX_FONT_ID_BOLD 10
#define MAIN_DISPLAY_FONT_TABLE_SIZE 11

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_BG_BLUE 5
#define GX_PIXELMAP_ID_BIG_BUTTON 6
#define GX_PIXELMAP_ID_BIG_BUTTON_PUSHED 7
#define GX_PIXELMAP_ID_BIG_BUTTON_ROBOT_ICON 8
#define GX_PIXELMAP_ID_BUTTON_GREEN_CORNER 9
#define GX_PIXELMAP_ID_CIRCLE_ICON_BOLT 10
#define GX_PIXELMAP_ID_CIRCLE_ICON_COMPRESS 11
#define GX_PIXELMAP_ID_CIRCLE_ICON_PALLET 12
#define GX_PIXELMAP_ID_CIRCLE_ICON_WRENCH 13
#define GX_PIXELMAP_ID_ICON_BOLT 14
#define GX_PIXELMAP_ID_ICON_INSPECT 15
#define GX_PIXELMAP_ID_ICON_OFF 16
#define GX_PIXELMAP_ID_ICON_PALLET 17
#define GX_PIXELMAP_ID_ICON_PIN 18
#define GX_PIXELMAP_ID_ICON_SHIELD_SMALL 19
#define GX_PIXELMAP_ID_ICON_THUMB_UP 20
#define GX_PIXELMAP_ID_ICON_TIMER 21
#define GX_PIXELMAP_ID_ICON_WRENCH 22
#define GX_PIXELMAP_ID_LEFT_SIDE_CHECK_MARK 23
#define GX_PIXELMAP_ID_MENU_BUTTON_C 24
#define GX_PIXELMAP_ID_MENU_BUTTON_C_PUSHED 25
#define GX_PIXELMAP_ID_MENU_BUTTON_LONG 26
#define GX_PIXELMAP_ID_MENU_BUTTON_LONG_PUSHED 27
#define GX_PIXELMAP_ID_MENU_ICON_HOME 28
#define GX_PIXELMAP_ID_MENU_ICON_HOME_PUSHED 29
#define GX_PIXELMAP_ID_MS_AZURE_LOGO_SMALL 30
#define GX_PIXELMAP_ID_OUTLINED_BUTTON_HOLDER 31
#define GX_PIXELMAP_ID_OUTLINED_BUTTON_HOLDER_LONG 32
#define GX_PIXELMAP_ID_OUTLINED_BUTTON_HOLDER_PUSHED 33
#define GX_PIXELMAP_ID_OUTLINED_BUTTON_HOLDER_SHORT 34
#define GX_PIXELMAP_ID_OUTLINED_BUTTON_INDICATOR 35
#define GX_PIXELMAP_ID_PROGRESS_BAR_BG 36
#define GX_PIXELMAP_ID_PROGRESS_FILL 37
#define GX_PIXELMAP_ID_RIGHT_SIDE_CIRCLE_PROGRESS_BG 38
#define GX_PIXELMAP_ID_S1 39
#define GX_PIXELMAP_ID_S10 40
#define GX_PIXELMAP_ID_S11 41
#define GX_PIXELMAP_ID_S12 42
#define GX_PIXELMAP_ID_S13 43
#define GX_PIXELMAP_ID_S14 44
#define GX_PIXELMAP_ID_S15 45
#define GX_PIXELMAP_ID_S16 46
#define GX_PIXELMAP_ID_S17 47
#define GX_PIXELMAP_ID_S18 48
#define GX_PIXELMAP_ID_S19 49
#define GX_PIXELMAP_ID_S2 50
#define GX_PIXELMAP_ID_S20 51
#define GX_PIXELMAP_ID_S21 52
#define GX_PIXELMAP_ID_S3 53
#define GX_PIXELMAP_ID_S4 54
#define GX_PIXELMAP_ID_S5 55
#define GX_PIXELMAP_ID_S6 56
#define GX_PIXELMAP_ID_S7 57
#define GX_PIXELMAP_ID_S8 58
#define GX_PIXELMAP_ID_S9 59
#define GX_PIXELMAP_ID_TOP_ICON_GEARS 60
#define GX_PIXELMAP_ID_TOP_ICON_GEARS_PUSYED 61
#define GX_PIXELMAP_ID_TOP_ICON_REFRESH 62
#define GX_PIXELMAP_ID_TOP_ICON_REFRESH_PUSHED 63
#define GX_PIXELMAP_ID_TOP_ICON_SHIELD 64
#define GX_PIXELMAP_ID_TOP_ICON_SHIELD_PUSHED 65
#define GX_PIXELMAP_ID_VERTICAL_DIVIDER 66
#define GX_PIXELMAP_ID_VERTICAL_DIVIDER_CONFIRMATION 67
#define MAIN_DISPLAY_PIXELMAP_TABLE_SIZE 68

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_2 1
#define GX_STRING_ID_STRING_3 2
#define GX_STRING_ID_STRING_4 3
#define GX_STRING_ID_STRING_6 4
#define GX_STRING_ID_STRING_7 5
#define GX_STRING_ID_STRING_8 6
#define GX_STRING_ID_STRING_9 7
#define GX_STRING_ID_STRING_10 8
#define GX_STRING_ID_STRING_12 9
#define GX_STRING_ID_STRING_13 10
#define GX_STRING_ID_STRING_14 11
#define GX_STRING_ID_STRING_15 12
#define GX_STRING_ID_STRING_16 13
#define GX_STRING_ID_STRING_17 14
#define GX_STRING_ID_STRING_18 15
#define GX_STRING_ID_STRING_19 16
#define GX_STRING_ID_STRING_20 17
#define GX_STRING_ID_STRING_21 18
#define GX_STRING_ID_STRING_22 19
#define GX_STRING_ID_STRING_23 20
#define GX_STRING_ID_STRING_24 21
#define GX_STRING_ID_STRING_25 22
#define GX_STRING_ID_STRING_26 23
#define GX_STRING_ID_STRING_29 24
#define GX_STRING_ID_STRING_31 25
#define GX_STRING_ID_STRING_32 26
#define GX_STRING_ID_STRING_33 27
#define GX_STRING_ID_STRING_34 28
#define GX_STRING_ID_STRING_35 29
#define GX_STRING_ID_STRING_36 30
#define GX_STRING_ID_STRING_37 31
#define GX_STRING_ID_STRING_38 32
#define GX_STRING_ID_STRING_42 33
#define GX_STRING_ID_STRING_44 34
#define GX_STRING_ID_STRING_45 35
#define GX_STRING_ID_STRING_47 36
#define GX_STRING_ID_STRING_49 37
#define GX_STRING_ID_STRING_50 38
#define GX_STRING_ID_STRING_52 39
#define GX_STRING_ID_STRING_56 40
#define GX_STRING_ID_STRING_57 41
#define GX_STRING_ID_STRING_58 42
#define GX_STRING_ID_STRING_59 43
#define GX_STRING_ID_STRING_60 44
#define GX_STRING_ID_STRING_62 45
#define GX_STRING_ID_STRING_63 46
#define GX_STRING_ID_STRING_64 47
#define GX_STRING_ID_STRING_65 48
#define GX_STRING_ID_STRING_66 49
#define GX_STRING_ID_STRING_67 50
#define GX_STRING_ID_STRING_69 51
#define GX_STRING_ID_STRING_5 52
#define GX_STRING_ID_STRING_11 53
#define GX_STRING_ID_STRING_27 54
#define GX_STRING_ID_STRING_39 55
#define MAIN_DISPLAY_STRING_TABLE_SIZE 56

#endif                                       /* sentry                         */
