/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.1.12.0                                              */
/*  Date (dd.mm.yyyy): 25. 8.2022   Time (hh:mm): 18:36                        */
/*******************************************************************************/


#ifndef _GUIX_MEDICAL_MOUSE_SUPPORT_MAIN_DISPLAY_RESOURCES_H_
#define _GUIX_MEDICAL_MOUSE_SUPPORT_MAIN_DISPLAY_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define MAIN_DISPLAY 0
#define MAIN_DISPLAY_COLOR_FORMAT GX_COLOR_FORMAT_24XRGB
#define MAIN_DISPLAY_X_RESOLUTION 640
#define MAIN_DISPLAY_Y_RESOLUTION 480
#define MAIN_DISPLAY_DEFAULT_THEME 0
#define MAIN_DISPLAY_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define MAIN_DISPLAY_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_YELLOW 29
#define GX_COLOR_ID_GREEN 30
#define GX_COLOR_ID_RED 31
#define GX_COLOR_ID_LIGHT_GRAY 32
#define GX_COLOR_ID_CHART_LINE 33
#define GX_COLOR_ID_WHITE 34
#define GX_COLOR_ID_ODD_ROW 35
#define GX_COLOR_ID_OFF_WHITE 36
#define GX_COLOR_ID_BLACK 37
#define GX_COLOR_ID_NEON 38
#define GX_COLOR_ID_WARN_YELLOW 39
#define MAIN_DISPLAY_COLOR_TABLE_SIZE 40

/* Font ID definitions                                                         */

#define GX_FONT_ID_BIG_NUMBER 4
#define GX_FONT_ID_MID_NUMBER 5
#define GX_FONT_ID_SMALL 6
#define GX_FONT_ID_SMALL_BOLD 7
#define GX_FONT_ID_SCREEN_LABEL 8
#define GX_FONT_ID_HR_NUMBER 9
#define MAIN_DISPLAY_FONT_TABLE_SIZE 10

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_BUTTON 5
#define GX_PIXELMAP_ID_BUTTON_ACTIVE 6
#define GX_PIXELMAP_ID_CARDIO_BG 7
#define GX_PIXELMAP_ID_CARDIO_DOT 8
#define GX_PIXELMAP_ID_CARDIO_LONG_BG 9
#define GX_PIXELMAP_ID_CARDIO_SLIDER_BG 10
#define GX_PIXELMAP_ID_CHART_ERASE 11
#define GX_PIXELMAP_ID_EXPRESS_LOGIC_LOGO 12
#define GX_PIXELMAP_ID_GUIX_LOGO 13
#define GX_PIXELMAP_ID_HOME 14
#define GX_PIXELMAP_ID_ICON_HEART_GRN_LARGE 15
#define GX_PIXELMAP_ID_ICON_HEART_GRN_MED 16
#define GX_PIXELMAP_ID_ICON_HEART_GRN_SMALL 17
#define GX_PIXELMAP_ID_ICON_HEART_RED_LARGE 18
#define GX_PIXELMAP_ID_ICON_HEART_RED_MED 19
#define GX_PIXELMAP_ID_ICON_HEART_RED_SMALL 20
#define GX_PIXELMAP_ID_ICON_MEDICATIONS 21
#define GX_PIXELMAP_ID_ICON_MEDICATIONS_ON 22
#define GX_PIXELMAP_ID_ICON_PATIENTS 23
#define GX_PIXELMAP_ID_ICON_PATIENTS_ON 24
#define GX_PIXELMAP_ID_ICON_VITALS 25
#define GX_PIXELMAP_ID_ICON_VITALS_ON 26
#define GX_PIXELMAP_ID_MOUSE 27
#define GX_PIXELMAP_ID_PERCENT 28
#define GX_PIXELMAP_ID_SLIDER_CARETS_ON 29
#define GX_PIXELMAP_ID_SLIDER_GREEN_BG 30
#define GX_PIXELMAP_ID_SLIDER_GREEN_BG_ON 31
#define GX_PIXELMAP_ID_SLIDER_INDICATOR 32
#define GX_PIXELMAP_ID_SLIDER_PURPLE_BG 33
#define GX_PIXELMAP_ID_SLIDER_PURPLE_BG_ON 34
#define GX_PIXELMAP_ID_SLIDER_RED_BG 35
#define GX_PIXELMAP_ID_SLIDER_RED_BG_ON 36
#define GX_PIXELMAP_ID_SLIDER_YELLOW_BG 37
#define GX_PIXELMAP_ID_SLIDER_YELLOW_BG_ON 38
#define GX_PIXELMAP_ID_TABLE_SCROLL_THUMB 39
#define MAIN_DISPLAY_PIXELMAP_TABLE_SIZE 40

/* String Ids                                                                  */

#define GX_STRING_ID_PATIENT_LIST 1
#define GX_STRING_ID_MEDICATIONS 2
#define GX_STRING_ID_VITALS 3
#define GX_STRING_ID_PATIENT_NAME 4
#define GX_STRING_ID_ROOM 5
#define GX_STRING_ID_MR_NUM 6
#define GX_STRING_ID_DEFAULT_RATE 7
#define GX_STRING_ID_ONE_WEEK 8
#define GX_STRING_ID_AVERAGE 9
#define GX_STRING_ID_MINIMUM 10
#define GX_STRING_ID_MAXIMUM 11
#define GX_STRING_ID_STRING_13 12
#define GX_STRING_ID_STRING_14 13
#define GX_STRING_ID_STRING_15 14
#define GX_STRING_ID_STRING_16 15
#define GX_STRING_ID_STRING_17 16
#define GX_STRING_ID_STRING_18 17
#define GX_STRING_ID_STRING_19 18
#define GX_STRING_ID_STRING_1 19
#define GX_STRING_ID_STRING_2 20
#define GX_STRING_ID_STRING_PERCENT 21
#define GX_STRING_ID_STRING_100 22
#define GX_STRING_ID_STRING_3 23
#define GX_STRING_ID_STRING_4 24
#define GX_STRING_ID_STRING_5 25
#define GX_STRING_ID_STRING_6 26
#define GX_STRING_ID_STRING_7 27
#define GX_STRING_ID_STRING_8 28
#define GX_STRING_ID_STRING_9 29
#define GX_STRING_ID_STRING_10 30
#define GX_STRING_ID_STRING_11 31
#define GX_STRING_ID_STRING_12 32
#define GX_STRING_ID_STRING_20 33
#define GX_STRING_ID_STRING_21 34
#define GX_STRING_ID_STRING_22 35
#define GX_STRING_ID_STRING_23 36
#define GX_STRING_ID_STRING_24 37
#define GX_STRING_ID_STRING_25 38
#define GX_STRING_ID_STRING_26 39
#define GX_STRING_ID_STRING_27 40
#define GX_STRING_ID_STRING_28 41
#define GX_STRING_ID_STRING_29 42
#define GX_STRING_ID_STRING_30 43
#define GX_STRING_ID_STRING_31 44
#define GX_STRING_ID_STRING_32 45
#define GX_STRING_ID_STRING_33 46
#define GX_STRING_ID_STRING_34 47
#define GX_STRING_ID_STRING_35 48
#define GX_STRING_ID_STRING_36 49
#define GX_STRING_ID_STRING_37 50
#define GX_STRING_ID_STRING_38 51
#define GX_STRING_ID_STRING_39 52
#define GX_STRING_ID_STRING_40 53
#define GX_STRING_ID_STRING_41 54
#define MAIN_DISPLAY_STRING_TABLE_SIZE 55

#endif                                       /* sentry                         */
