/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.2.1.2                                               */
/*  Date (dd.mm.yyyy):  6. 6.2023   Time (hh:mm): 09:36                        */
/*******************************************************************************/


#include "gx_api.h"
#include "screenshot_to_bitmap_332rgb_resources.h"

/* Color Table                                                                 */

GX_CONST GX_COLOR Primary_theme_1_color_table[] =
{
    0x00000000,
    0x0000006d,
    0x000000ff,
    0x00000091,
    0x00000072,
    0x00000000,
    0x000000ff,
    0x00000002,
    0x00000092,
    0x000000db,
    0x000000f9,
    0x000000ff,
    0x000000fe,
    0x00000000,
    0x000000b6,
    0x0000006d,
    0x000000ff,
    0x000000ff,
    0x00000000,
    0x000000db,
    0x000000ff,
    0x00000000,
    0x00000092,
    0x000000db,
    0x000000f9,
    0x000000b6,
    0x0000006d,
    0x000000ff,
    0x0000006d,
    0x000000ff,
    0x00000000,
    0x00000000,
    0x000000ff,
    0x000000ff,
    0x00000000
};


/* Font Table                                                                  */


extern GX_CONST GX_FONT _gx_system_font_mono;
GX_CONST GX_FONT *Primary_theme_1_font_table[] =
{
    &_gx_system_font_mono,
    &_gx_system_font_mono,
    &_gx_system_font_mono,
    &_gx_system_font_mono
};

/* Pixelmap data definitions                                                   */


/* THEME_1_RADIO_ON pixelmap data                                              */

static GX_CONST USHORT PRIMARY_THEME_1_RADIO_ON_pixelmap_data[194] =
{
    0x8003, 0x00ff, 0x0001, 0x80ff, 0xccbb, 0x8002, 0xff72, 0x0001, 0xff96, 0xa3bb, 
    0x8004, 0x00ff, 0x8002, 0x00ff, 0x0002, 0x80db, 0xff72, 0xffd6, 0x8003, 0xfff5, 
    0x0002, 0xffd6, 0xff72, 0x80ff, 0x8002, 0x00ff, 0x000f, 0x00ff, 0x00ff, 0xccbb, 
    0xffb6, 0xfff5, 0xffb9, 0xff7c, 0xff5c, 0xff5c, 0xff7c, 0xffb9, 0xfff5, 0xff96, 
    0xccdb, 0x00ff, 0x00ff, 0x0004, 0x00ff, 0x80db, 0xffb6, 0xfff5, 0xff7c, 0x8005, 
    0xff5c, 0x0004, 0xff7c, 0xfff5, 0xff96, 0x80ff, 0x00ff, 0x0003, 0x33ff, 0xff72, 
    0xfff5, 0xff7c, 0x8007, 0xff5c, 0x0003, 0xff7c, 0xfff5, 0xff72, 0x00ff, 0x0002, 
    0xccbb, 0xfffa, 0xffb9, 0x8009, 0xff5c, 0x0002, 0xfffa, 0xffd6, 0xa4db, 0x0002, 
    0xff96, 0xfff5, 0xff7c, 0x8009, 0xff5c, 0x0002, 0xffbd, 0xfffa, 0xff97, 0x0001, 
    0xff96, 0xfff5, 0x800b, 0xff5c, 0x0001, 0xfff5, 0xff96, 0x0001, 0xff96, 0xfff5, 
    0x800b, 0xff5c, 0x0001, 0xfff5, 0xff96, 0x0002, 0xff96, 0xfff5, 0xff7c, 0x8009, 
    0xff5c, 0x0002, 0xff7c, 0xfffa, 0xff97, 0x0002, 0xccbb, 0xfffa, 0xff7c, 0x8009, 
    0xff5c, 0x0002, 0xfffa, 0xffd6, 0x83db, 0x0003, 0x00ff, 0xff72, 0xfff5, 0xff7c, 
    0x8007, 0xff5c, 0x0003, 0xff7c, 0xfff5, 0xff72, 0x00ff, 0x0004, 0x00ff, 0xccdb, 
    0xffb6, 0xfff5, 0xff7c, 0x8005, 0xff5c, 0x0004, 0xff7c, 0xfff5, 0xff96, 0x80ff, 
    0x00ff, 0x000f, 0x00ff, 0x00ff, 0xccbb, 0xffb6, 0xfff5, 0xffb9, 0xff7c, 0xff5c, 
    0xff5c, 0xff7c, 0xfffa, 0xfff5, 0xff96, 0xccdb, 0x00ff, 0x00ff, 0x8002, 0x00ff, 
    0x0002, 0xccdb, 0xff72, 0xffd6, 0x8003, 0xfff5, 0x0002, 0xffd6, 0xff72, 0x80ff, 
    0x8002, 0x00ff, 0x8003, 0x00ff, 0x0006, 0x33ff, 0xccbb, 0xff92, 0xff72, 0xff72, 
    0xff96, 0xccbb, 0x8004, 0x00ff
};
GX_CONST GX_PIXELMAP PRIMARY_THEME_1_RADIO_ON_pixelmap =
{
    0x00000001,                              /* major version                  */
    0x00000000,                              /* minor version                  */
    GX_PIXELMAP_COMPRESSED|GX_PIXELMAP_ALPHA,         /* flags                 */
    GX_COLOR_FORMAT_8BIT_PACKED_PIXEL,         /* Format                       */
    (GX_UBYTE *) PRIMARY_THEME_1_RADIO_ON_pixelmap_data,
    sizeof(PRIMARY_THEME_1_RADIO_ON_pixelmap_data),    /* the size of pixelmap_data*/
    NULL,
    0,                                       /* auxiliary data size            */
    0x00,                                    /* used for transparent iamges    */
    16,                                      /* width in pixel                 */
    16                                       /* height in pixel                */
};

/* THEME_1_RADIO_OFF pixelmap data                                             */

static GX_CONST USHORT PRIMARY_THEME_1_RADIO_OFF_pixelmap_data[180] =
{
    0x8003, 0x00ff, 0x0001, 0xffff, 0xb3bb, 0x8002, 0xff72, 0x0001, 0xff96, 0xb3bb, 
    0x8004, 0x00ff, 0x8002, 0x00ff, 0x0002, 0x80db, 0xff72, 0xffd6, 0x8003, 0xfff5, 
    0x0002, 0xffd6, 0xff72, 0x33ff, 0x8002, 0x00ff, 0x0005, 0x00ff, 0x00ff, 0xb3bb, 
    0xffb6, 0xfff5, 0xfffa, 0x8003, 0xffff, 0x0005, 0xfffa, 0xfff5, 0xff96, 0xb3db, 
    0x00ff, 0x00ff, 0x0003, 0x00ff, 0x80db, 0xffb6, 0xfff5, 0x8007, 0xffff, 0x0003, 
    0xfff5, 0xff96, 0x33ff, 0x00ff, 0x0002, 0x33ff, 0xff72, 0xfff5, 0x8009, 0xffff, 
    0x0002, 0xfff5, 0xff72, 0x00ff, 0x0002, 0xb3bb, 0xfffa, 0xfffa, 0x8009, 0xffff, 
    0x0002, 0xfffa, 0xffd6, 0x80db, 0x0001, 0xff96, 0xfff5, 0x800b, 0xffff, 0x0001, 
    0xfffa, 0xff97, 0x0001, 0xff96, 0xfff5, 0x800b, 0xffff, 0x0001, 0xfff5, 0xff96, 
    0x0001, 0xff96, 0xfff5, 0x800b, 0xffff, 0x0001, 0xfff5, 0xff96, 0x0001, 0xff96, 
    0xfff5, 0x800b, 0xffff, 0x0001, 0xfffa, 0xff97, 0x0002, 0xb3bb, 0xfffa, 0xfffa, 
    0x8009, 0xffff, 0x0002, 0xfffa, 0xffd6, 0x80db, 0x0002, 0x00ff, 0xff72, 0xfff5, 
    0x8009, 0xffff, 0x0002, 0xfff5, 0xff72, 0x00ff, 0x0003, 0x00ff, 0x80db, 0xffb6, 
    0xfff5, 0x8007, 0xffff, 0x0003, 0xfff5, 0xff96, 0x33ff, 0x00ff, 0x0005, 0x00ff, 
    0x00ff, 0xb3bb, 0xffb6, 0xfff5, 0xfffa, 0x8003, 0xffff, 0x0005, 0xfffa, 0xfff5, 
    0xff96, 0xb3db, 0x00ff, 0x00ff, 0x8002, 0x00ff, 0x0002, 0x80db, 0xff72, 0xffd6, 
    0x8003, 0xfff5, 0x0002, 0xffd6, 0xff72, 0x80ff, 0x8002, 0x00ff, 0x8003, 0x00ff, 
    0x0006, 0x33ff, 0xb3bb, 0xff92, 0xff72, 0xff72, 0xff96, 0xb3bb, 0x8004, 0x00ff

};
GX_CONST GX_PIXELMAP PRIMARY_THEME_1_RADIO_OFF_pixelmap =
{
    0x00000001,                              /* major version                  */
    0x00000000,                              /* minor version                  */
    GX_PIXELMAP_COMPRESSED|GX_PIXELMAP_ALPHA,         /* flags                 */
    GX_COLOR_FORMAT_8BIT_PACKED_PIXEL,         /* Format                       */
    (GX_UBYTE *) PRIMARY_THEME_1_RADIO_OFF_pixelmap_data,
    sizeof(PRIMARY_THEME_1_RADIO_OFF_pixelmap_data),    /* the size of pixelmap_data*/
    NULL,
    0,                                       /* auxiliary data size            */
    0x00,                                    /* used for transparent iamges    */
    16,                                      /* width in pixel                 */
    16                                       /* height in pixel                */
};

/* THEME_1_CHECKBOX_ON pixelmap data                                           */

static GX_CONST GX_UBYTE PRIMARY_THEME_1_CHECKBOX_ON_pixelmap_data[213] =
{
    0x8f, 0x0a, 0x02, 0x0a, 0xba, 0xfb, 0x89, 0xda, 0x02, 0xd9, 0xb5, 0x0a, 0x02, 
    0x0a, 0xfb, 0xff, 0x83, 0xfe, 0x01, 0xfa, 0xfa, 0x84, 0xfe, 0x01, 0xd5, 0x0a, 
    0x04, 0x0a, 0xda, 0xfe, 0xfe, 0xff, 0x83, 0xfe, 0x06, 0xff, 0xff, 0xba, 0xda, 
    0xfe, 0xd5, 0x0a, 0x02, 0x0a, 0xda, 0xfe, 0x86, 0xff, 0x05, 0xdf, 0x34, 0x99, 
    0xfe, 0xd5, 0x0a, 0x01, 0x0a, 0xda, 0x86, 0xff, 0x06, 0xdf, 0x34, 0x10, 0xb9, 
    0xfe, 0xd5, 0x0a, 0x04, 0x0a, 0xda, 0xff, 0xba, 0x55, 0x82, 0xff, 0x07, 0xdf, 
    0x34, 0x14, 0x10, 0xb9, 0xfe, 0xd5, 0x0a, 0x0f, 0x0a, 0xda, 0xff, 0xba, 0x10, 
    0x79, 0xff, 0xbe, 0x55, 0x10, 0x10, 0x9a, 0xfa, 0xfa, 0xd5, 0x0a, 0x0f, 0x0a, 
    0xda, 0xff, 0xba, 0x10, 0x10, 0x9a, 0x55, 0x10, 0x34, 0x79, 0xff, 0xfe, 0xf9, 
    0xd5, 0x0a, 0x0f, 0x0a, 0xda, 0xfe, 0xba, 0x34, 0x14, 0x10, 0x10, 0x34, 0x75, 
    0xff, 0xff, 0xfa, 0xf9, 0xd5, 0x0a, 0x08, 0x0a, 0xda, 0xfe, 0xff, 0xdf, 0x34, 
    0x14, 0x10, 0x79, 0x82, 0xff, 0x03, 0xfa, 0xf4, 0xd5, 0x0a, 0x07, 0x0a, 0xd5, 
    0xfa, 0xfe, 0xff, 0xdf, 0x34, 0x9a, 0x83, 0xff, 0x03, 0xfa, 0xf4, 0xd5, 0x0a, 
    0x08, 0x0a, 0xd5, 0xf9, 0xfa, 0xfe, 0xff, 0xba, 0xfa, 0xfe, 0x82, 0xfa, 0x03, 
    0xf5, 0xf4, 0xd5, 0x0a, 0x01, 0x0a, 0xd5, 0x82, 0xf9, 0x04, 0xfa, 0xfe, 0xfa, 
    0xf9, 0xf9, 0x83, 0xf4, 0x01, 0xd4, 0x0a, 0x01, 0x0a, 0xb5, 0x8a, 0xd5, 0x02, 
    0xd4, 0xb1, 0x0a, 0x8f, 0x0a
};
GX_CONST GX_PIXELMAP PRIMARY_THEME_1_CHECKBOX_ON_pixelmap =
{
    0x00000001,                              /* major version                  */
    0x00000000,                              /* minor version                  */
    GX_PIXELMAP_COMPRESSED,                  /* flags                          */
    GX_COLOR_FORMAT_8BIT_PACKED_PIXEL,         /* Format                       */
    (GX_UBYTE *) PRIMARY_THEME_1_CHECKBOX_ON_pixelmap_data,
    sizeof(PRIMARY_THEME_1_CHECKBOX_ON_pixelmap_data),    /* the size of pixelmap_data*/
    NULL,
    0,                                       /* auxiliary data size            */
    0x00,                                    /* used for transparent iamges    */
    16,                                      /* width in pixel                 */
    16                                       /* height in pixel                */
};

/* THEME_1_CHECKBOX_OFF pixelmap data                                          */

static GX_CONST GX_UBYTE PRIMARY_THEME_1_CHECKBOX_OFF_pixelmap_data[172] =
{
    0x8f, 0x0a, 0x02, 0x0a, 0xba, 0xfb, 0x86, 0xda, 0x83, 0xd5, 0x01, 0xb5, 0x0a, 
    0x02, 0x0a, 0xfb, 0xff, 0x83, 0xfe, 0x00, 0xfa, 0x85, 0xf9, 0x01, 0xd5, 0x0a, 
    0x01, 0x0a, 0xda, 0x83, 0xfe, 0x85, 0xfa, 0x03, 0xf9, 0xf9, 0xd5, 0x0a, 0x03, 
    0x0a, 0xda, 0xfe, 0xfe, 0x87, 0xff, 0x03, 0xfa, 0xf9, 0xd5, 0x0a, 0x03, 0x0a, 
    0xda, 0xfe, 0xfe, 0x87, 0xff, 0x03, 0xfa, 0xf9, 0xd5, 0x0a, 0x03, 0x0a, 0xda, 
    0xfe, 0xfa, 0x87, 0xff, 0x03, 0xfa, 0xf8, 0xd5, 0x0a, 0x03, 0x0a, 0xda, 0xfa, 
    0xfa, 0x87, 0xff, 0x03, 0xfa, 0xf8, 0xd5, 0x0a, 0x03, 0x0a, 0xda, 0xf9, 0xfa, 
    0x87, 0xff, 0x03, 0xfa, 0xf4, 0xd5, 0x0a, 0x03, 0x0a, 0xda, 0xf9, 0xfa, 0x87, 
    0xff, 0x03, 0xf9, 0xf4, 0xd5, 0x0a, 0x03, 0x0a, 0xd5, 0xf9, 0xfa, 0x87, 0xff, 
    0x03, 0xf9, 0xf4, 0xd5, 0x0a, 0x03, 0x0a, 0xd5, 0xf9, 0xfa, 0x87, 0xff, 0x03, 
    0xf9, 0xf4, 0xd5, 0x0a, 0x03, 0x0a, 0xd5, 0xf9, 0xf9, 0x84, 0xfa, 0x82, 0xf9, 
    0x03, 0xf5, 0xf4, 0xd5, 0x0a, 0x01, 0x0a, 0xd5, 0x83, 0xf9, 0x01, 0xf8, 0xf8, 
    0x85, 0xf4, 0x01, 0xd4, 0x0a, 0x01, 0x0a, 0xb5, 0x8a, 0xd5, 0x02, 0xd4, 0xb1, 
    0x0a, 0x8f, 0x0a
};
GX_CONST GX_PIXELMAP PRIMARY_THEME_1_CHECKBOX_OFF_pixelmap =
{
    0x00000001,                              /* major version                  */
    0x00000000,                              /* minor version                  */
    GX_PIXELMAP_COMPRESSED,                  /* flags                          */
    GX_COLOR_FORMAT_8BIT_PACKED_PIXEL,         /* Format                       */
    (GX_UBYTE *) PRIMARY_THEME_1_CHECKBOX_OFF_pixelmap_data,
    sizeof(PRIMARY_THEME_1_CHECKBOX_OFF_pixelmap_data),    /* the size of pixelmap_data*/
    NULL,
    0,                                       /* auxiliary data size            */
    0x00,                                    /* used for transparent iamges    */
    16,                                      /* width in pixel                 */
    16                                       /* height in pixel                */
};

/* Pixelmap Table                                                              */


GX_CONST GX_PIXELMAP *Primary_theme_1_pixelmap_table[] =
{
    GX_NULL,
    &PRIMARY_THEME_1_RADIO_ON_pixelmap,
    &PRIMARY_THEME_1_RADIO_OFF_pixelmap,
    &PRIMARY_THEME_1_CHECKBOX_ON_pixelmap,
    &PRIMARY_THEME_1_CHECKBOX_OFF_pixelmap
};

/* String values                                                               */

GX_CONST GX_UBYTE Primary_STRING_3_English[] = "checkbox";
GX_CONST GX_UBYTE Primary_STRING_5_English[] = "prompt";
GX_CONST GX_UBYTE Primary_STRING_30_English[] = "pixelmap prompt";
GX_CONST GX_UBYTE Primary_STRING_31_English[] = "text_view";
GX_CONST GX_UBYTE Primary_STRING_63_English[] = "January";
GX_CONST GX_UBYTE Primary_STRING_69_English[] = "February";
GX_CONST GX_UBYTE Primary_STRING_70_English[] = "March";
GX_CONST GX_UBYTE Primary_STRING_71_English[] = "April";
GX_CONST GX_UBYTE Primary_STRING_72_English[] = "May";
GX_CONST GX_UBYTE Primary_STRING_73_English[] = "June";
GX_CONST GX_UBYTE Primary_STRING_74_English[] = "July";
GX_CONST GX_UBYTE Primary_STRING_75_English[] = "August";
GX_CONST GX_UBYTE Primary_STRING_76_English[] = "September";
GX_CONST GX_UBYTE Primary_STRING_77_English[] = "October";
GX_CONST GX_UBYTE Primary_STRING_78_English[] = "November";
GX_CONST GX_UBYTE Primary_STRING_79_English[] = "December";
GX_CONST GX_UBYTE Primary_STRING_92_English[] = "text button";
GX_CONST GX_UBYTE Primary_STRING_93_English[] = "radio button";
GX_CONST GX_UBYTE Primary_STRING_1_English[] = "Texts";
GX_CONST GX_UBYTE Primary_STRING_2_English[] = "Multi\rline\rtext button";
GX_CONST GX_UBYTE Primary_STRING_4_English[] = "scroll_wheel_runtime";
GX_CONST GX_UBYTE Primary_STRING_6_English[] = "scroll_wheel";

/* String Table for Primary language English                                   */

GX_CONST GX_STRING Primary_English_string_table[23] =
{
    {GX_NULL, 0},
    {(GX_CONST GX_CHAR *)Primary_STRING_3_English, sizeof(Primary_STRING_3_English) - 1},
    {(GX_CONST GX_CHAR *)Primary_STRING_5_English, sizeof(Primary_STRING_5_English) - 1},
    {(GX_CONST GX_CHAR *)Primary_STRING_30_English, sizeof(Primary_STRING_30_English) - 1},
    {(GX_CONST GX_CHAR *)Primary_STRING_31_English, sizeof(Primary_STRING_31_English) - 1},
    {(GX_CONST GX_CHAR *)Primary_STRING_63_English, sizeof(Primary_STRING_63_English) - 1},
    {(GX_CONST GX_CHAR *)Primary_STRING_69_English, sizeof(Primary_STRING_69_English) - 1},
    {(GX_CONST GX_CHAR *)Primary_STRING_70_English, sizeof(Primary_STRING_70_English) - 1},
    {(GX_CONST GX_CHAR *)Primary_STRING_71_English, sizeof(Primary_STRING_71_English) - 1},
    {(GX_CONST GX_CHAR *)Primary_STRING_72_English, sizeof(Primary_STRING_72_English) - 1},
    {(GX_CONST GX_CHAR *)Primary_STRING_73_English, sizeof(Primary_STRING_73_English) - 1},
    {(GX_CONST GX_CHAR *)Primary_STRING_74_English, sizeof(Primary_STRING_74_English) - 1},
    {(GX_CONST GX_CHAR *)Primary_STRING_75_English, sizeof(Primary_STRING_75_English) - 1},
    {(GX_CONST GX_CHAR *)Primary_STRING_76_English, sizeof(Primary_STRING_76_English) - 1},
    {(GX_CONST GX_CHAR *)Primary_STRING_77_English, sizeof(Primary_STRING_77_English) - 1},
    {(GX_CONST GX_CHAR *)Primary_STRING_78_English, sizeof(Primary_STRING_78_English) - 1},
    {(GX_CONST GX_CHAR *)Primary_STRING_79_English, sizeof(Primary_STRING_79_English) - 1},
    {(GX_CONST GX_CHAR *)Primary_STRING_92_English, sizeof(Primary_STRING_92_English) - 1},
    {(GX_CONST GX_CHAR *)Primary_STRING_93_English, sizeof(Primary_STRING_93_English) - 1},
    {(GX_CONST GX_CHAR *)Primary_STRING_1_English, sizeof(Primary_STRING_1_English) - 1},
    {(GX_CONST GX_CHAR *)Primary_STRING_2_English, sizeof(Primary_STRING_2_English) - 1},
    {(GX_CONST GX_CHAR *)Primary_STRING_4_English, sizeof(Primary_STRING_4_English) - 1},
    {(GX_CONST GX_CHAR *)Primary_STRING_6_English, sizeof(Primary_STRING_6_English) - 1}
};

/*  Language Table                                                             */


GX_CONST GX_STRING *Primary_language_table[1] = 
{
    Primary_English_string_table,
};

GX_THEME Primary_theme_1 =
{
    (GX_COLOR *) Primary_theme_1_color_table,
    (GX_FONT **) Primary_theme_1_font_table,
    (GX_PIXELMAP **) Primary_theme_1_pixelmap_table,
    NULL,
    {
        20,                                  /* scroll width                   */
        18,                                  /* thumb width                    */
        20,                                  /* thumb travel min               */
        20,                                  /* thumb travel max               */
        4,                                   /* thumb border style             */
        0,                                   /* scroll fill pixelmap           */
        0,                                   /* scroll thumb pixelmap          */
        0,                                   /* scroll up pixelmap             */
        0,                                   /* scroll down pixelmap           */
        GX_COLOR_ID_SCROLL_BUTTON,           /* scroll thumb color             */
        GX_COLOR_ID_CANVAS,                  /* scroll thumb border color      */
        GX_COLOR_ID_SCROLL_BUTTON,           /* scroll button color            */
    },
    {
        20,                                  /* scroll width                   */
        18,                                  /* thumb width                    */
        20,                                  /* thumb travel min               */
        20,                                  /* thumb travel max               */
        4,                                   /* thumb border style             */
        0,                                   /* scroll fill pixelmap           */
        0,                                   /* scroll thumb pixelmap          */
        0,                                   /* scroll up pixelmap             */
        0,                                   /* scroll down pixelmap           */
        GX_COLOR_ID_SCROLL_BUTTON,           /* scroll thumb color             */
        GX_COLOR_ID_CANVAS,                  /* scroll thumb border color      */
        GX_COLOR_ID_SCROLL_BUTTON,           /* scroll button color            */
    },
    GX_SCROLLBAR_RELATIVE_THUMB|GX_SCROLLBAR_END_BUTTONS|GX_SCROLLBAR_VERTICAL,
    GX_SCROLLBAR_RELATIVE_THUMB|GX_SCROLLBAR_END_BUTTONS|GX_SCROLLBAR_HORIZONTAL,
    35,                                      /* color table size               */
    4,                                       /* font table size                */
    5,                                       /* pixelmap table size            */
    0                                        /* palette size                   */

};
GX_CONST GX_THEME *Primary_theme_table[1] =
{
    &Primary_theme_1
};

