/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.1.8.0                                               */
/*  Date (dd.mm.yyyy): 26. 7.2021   Time (hh:mm): 15:32                        */
/*******************************************************************************/


#ifndef _GUIX_SPRITE_DISPLAY_1_RESOURCES_H_
#define _GUIX_SPRITE_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_24XRGB
#define DISPLAY_1_X_RESOLUTION 640
#define DISPLAY_1_Y_RESOLUTION 480
#define DISPLAY_1_DEFAULT_THEME 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_BLACK 29
#define GX_COLOR_ID_WHITE 30
#define GX_COLOR_ID_RED 31
#define GX_COLOR_ID_GREEN 32
#define GX_COLOR_ID_LIGHTGRAY 33
#define DISPLAY_1_COLOR_TABLE_SIZE 34

/* Font ID definitions                                                         */

#define DISPLAY_1_FONT_TABLE_SIZE 4

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_BIRD_01 5
#define GX_PIXELMAP_ID_BIRD_02 6
#define GX_PIXELMAP_ID_BIRD_03 7
#define GX_PIXELMAP_ID_BIRD_04 8
#define GX_PIXELMAP_ID_BIRD_05 9
#define GX_PIXELMAP_ID_GX_SLIDER_BG_HORIZONTAL 10
#define GX_PIXELMAP_ID_GX_SLIDER_NEEDLES_HORIZONTAL 11
#define GX_PIXELMAP_ID_MS_AZURE_LOGO_SMALL 12
#define GX_PIXELMAP_ID_SKY 13
#define DISPLAY_1_PIXELMAP_TABLE_SIZE 14

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_1 1
#define GX_STRING_ID_STRING_2 2
#define GX_STRING_ID_STRING_3 3
#define GX_STRING_ID_STRING_4 4
#define GX_STRING_ID_STRING_5 5
#define GX_STRING_ID_STRING_6 6
#define GX_STRING_ID_STRING_7 7
#define GX_STRING_ID_STRING_8 8
#define GX_STRING_ID_STRING_9 9
#define GX_STRING_ID_STRING_10 10
#define GX_STRING_ID_STRING_11 11
#define GX_STRING_ID_STRING_12 12
#define GX_STRING_ID_STRING_13 13
#define GX_STRING_ID_STRING_14 14
#define GX_STRING_ID_STRING_15 15
#define GX_STRING_ID_STRING_16 16
#define DISPLAY_1_STRING_TABLE_SIZE 17

#endif                                       /* sentry                         */
