/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.1.12.0                                              */
/*  Date (dd.mm.yyyy): 25. 8.2022   Time (hh:mm): 18:40                        */
/*******************************************************************************/


#ifndef _PIXELMAP_CLIP_16BPP_MAIN_DISPLAY_RESOURCES_H_
#define _PIXELMAP_CLIP_16BPP_MAIN_DISPLAY_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define MAIN_DISPLAY 0
#define MAIN_DISPLAY_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define MAIN_DISPLAY_X_RESOLUTION 320
#define MAIN_DISPLAY_Y_RESOLUTION 240
#define MAIN_DISPLAY_DEFAULT_THEME 0
#define MAIN_DISPLAY_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define MAIN_DISPLAY_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_GREEN 29
#define GX_COLOR_ID_BLUE 30
#define GX_COLOR_ID_LIGHT_PINK 31
#define GX_COLOR_ID_LIGHT_YELLOW 32
#define MAIN_DISPLAY_COLOR_TABLE_SIZE 33

/* Font ID definitions                                                         */

#define MAIN_DISPLAY_FONT_TABLE_SIZE 4

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_CAL_POPPY_200 5
#define GX_PIXELMAP_ID_RAINBOW200_ALPHA0_COMPRESS 6
#define GX_PIXELMAP_ID_RAINBOW200_ALPHA0_NONCOMPRESS 7
#define GX_PIXELMAP_ID_RAINBOW200_NOALPHA_COMPRESS 8
#define GX_PIXELMAP_ID_RAINBOW200_NOALPHA_NONCOMPRESS 9
#define MAIN_DISPLAY_PIXELMAP_TABLE_SIZE 10

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_1 1
#define GX_STRING_ID_STRING_2 2
#define GX_STRING_ID_STRING_3 3
#define GX_STRING_ID_STRING_4 4
#define GX_STRING_ID_STRING_5 5
#define GX_STRING_ID_STRING_6 6
#define GX_STRING_ID_STRING_7 7
#define GX_STRING_ID_STRING_8 8
#define GX_STRING_ID_STRING_9 9
#define GX_STRING_ID_STRING_10 10
#define GX_STRING_ID_STRING_11 11
#define GX_STRING_ID_STRING_12 12
#define GX_STRING_ID_STRING_13 13
#define GX_STRING_ID_STRING_14 14
#define GX_STRING_ID_STRING_15 15
#define GX_STRING_ID_STRING_16 16
#define GX_STRING_ID_STRING_17 17
#define GX_STRING_ID_STRING_18 18
#define GX_STRING_ID_STRING_19 19
#define GX_STRING_ID_STRING_20 20
#define GX_STRING_ID_STRING_21 21
#define GX_STRING_ID_STRING_22 22
#define GX_STRING_ID_STRING_23 23
#define GX_STRING_ID_STRING_24 24
#define GX_STRING_ID_STRING_25 25
#define GX_STRING_ID_STRING_26 26
#define GX_STRING_ID_STRING_27 27
#define MAIN_DISPLAY_STRING_TABLE_SIZE 28

#endif                                       /* sentry                         */
