/***************************************************************************
 * Copyright (c) 2024 Microsoft Corporation
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **************************************************************************/
// Some portions generated by Copilot (Claude Sonnet 4.6).


/**************************************************************************/
/**************************************************************************/
/**                                                                       */
/** GUIX Component                                                        */
/**                                                                       */
/**   System Management (System)                                          */
/**                                                                       */
/**************************************************************************/

#define GX_SOURCE_CODE


/* Include necessary system files.  */

#include "gx_api.h"
#include "gx_system.h"


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    _gx_system_error_process                            PORTABLE C      */
/*                                                           6.1          */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Kenneth Maxwell, Microsoft Corporation                              */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    This function processes internal GUIX system errors. The main       */
/*    purpose of this routine is for troubleshooting, e.g., this routine  */
/*    keeps track of the number of system errors and the last system      */
/*    error code. In addition, the user may set a breakpoint on this      */
/*    routine to troubleshoot system errors.                              */
/*                                                                        */
/*  INPUT                                                                 */
/*                                                                        */
/*    error_code                            System error code             */
/*                                                                        */
/*  OUTPUT                                                                */
/*                                                                        */
/*    None                                                                */
/*                                                                        */
/*  CALLS                                                                 */
/*                                                                        */
/*    None                                                                */
/*                                                                        */
/*  CALLED BY                                                             */
/*                                                                        */
/*    GUIX Internal Code                                                  */
/*                                                                        */
/**************************************************************************/
VOID  _gx_system_error_process(UINT error_code)
{

    /* Increment the total number of system errors.  */
    _gx_system_error_count++;

    /* Remember the last system error code.  */
    _gx_system_last_error =  error_code;

#ifdef GX_DISABLE_THREADX_BINDING
#ifdef GX_ENABLE_ERROR_CALLBACK
    GX_GENERIC_ERROR_PROCESS(error_code, _gx_system_error_count);
#endif
#endif
}

