# This is a basic workflow that is manually triggered

name: GUIX Studio MSIX Package

# Controls when the action will run.
on:
  workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "linux_job"
  generate_msix_upload_file:
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
      
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Generate GUIX Studio package upload file
      run: scripts/build_guix_studio_msix_package.cmd

    - name: Upload GUIX Studio package upload file
      uses: actions/upload-artifact@v3.1.3
      with:
        name: GUIXStudioPackages
        path: guix_studio/build/vs_2019/msix_package_project/AppPackages

    